### ISSUE TITLE
Fail to build 3D map with 4 Kinects

### ISSUE THREAD

**Issue by MetalSlugxx** [googlecartographer/cartographer_ros#1006]
Hi, I am using 4 kinects to build 3D map with imu, but fail to generate a map. 
Cartographer node has received imu data topic(imu/data_raw) and point cloud topic(points2_1/points2_2/points2_3/points2_4) generated from four kinect cameras at different positions and orientations. However in the rviz, the point cloud only shows around the origin of "map" and "odom". The other links, such as base_link, imu_link and 4 kinect links just appear anywhere randomly away from the mapping center. 

And the terminal has the output infomation "[ INFO] [1536641871.998100393]: I0911 12:57:51.000000  7985 local_trajectory_builder_3d.cc:78] Range data collator filling buffer."

1. The "rosbag_validate" output result Gist link is [here](https://gist.github.com/MetalSlugxx/65116f0fe9e56ccd6009911245420003).

2. The configuration, launch, and URDF files link is [here](https://github.com/MetalSlugxx/cartographer_ros_kinect/tree/master/cartographer_ros/cartographer_ros).
The launch file to run is [demo_kinect_3d.launch](https://github.com/MetalSlugxx/cartographer_ros_kinect/blob/master/cartographer_ros/cartographer_ros/launch/demo_kinect_3d.launch).

3. The tested rosbag is uploaded to [GoogleDrive]( https://drive.google.com/open?id=1CHydEnjml7zsVz28aSPzShwB3m6QEqJJ).

Any idea about that? Thank you in advance for your help and providing such good SLAM system!

**Comment by MetalSlugxx** [comment]
Oh, I made a mistake on sim_time. I successfully build the map but still can't close the loop, so the result isn't good enough. I think it's the problem of parameters and imu data. I'll try on solving that.

**Comment by christophTUM** [comment]
What mistake was that?
