### ISSUE TITLE
cannot switch to pure localization

### ISSUE THREAD

**Issue by danielm1405** [googlecartographer/cartographer_ros#1015]
Hi, 
I am trying to run cartographer in pure 2D localization. To achieve it I set 
`TRAJECTORY_BUILDER.pure_localization = true`
in my configuration file. However I receive fatal error:
`Check failed: 1 == reference_counts_.count(key) (1 vs. 0) Key 'pure_localization' was used the wrong number of times.`
How should to set to pure localization mode?

**Comment by cschuet** [comment]
That option changed. You have to set 

```
TRAJECTORY_BUILDER.pure_localization_trimmer = {
  max_submaps_to_keep = 3,
}
```

**Comment by danielm1405** [comment]
Is it possible that the simple environment causes the localization problem? Should I expect better results while using pure localization in more complex surrounding?

**Comment by cschuet** [comment]
I am not sure I understand the visualization. When you look in rviz do you see two trajectories? Trajectory 0 should contain the map you are trying to localize against. Trajectory 1 should be a trajectory that contains only 3 submaps (when the next one is created the oldest one should disappear).

Can you enable only INTER constraint visualizations? Are there any constraints going from trajectory 0 to trajectory 1?

**Comment by danielm1405** [comment]
The issue above occurs while trying to use offline localization (playing from .bag file), however for some reason robot localizes itself perfectly while running online version. So the problem lays somewhere in the bag file. Do you know what can be the source of the problem?
