### ISSUE TITLE
Drifting

### ISSUE THREAD

**Issue by ingmarbergmann** [googlecartographer/cartographer_ros#1022]
Hello,

has anyone an idea what I might do wrong by tuning the parameters?The trajectory still seems to drift.
In validate_record1 you will find the setup.

Thank you in advance! 

All files are attached in the link.
https://drive.google.com/drive/folders/14VAzrnkP8tlPtxKIff6Oc1VzJu6j6aWY?usp=sharing
![cartographer](https://user-images.githubusercontent.com/43322475/46811269-b3203b80-cd72-11e8-9d30-352458581f44.png)

**Comment by ChunJyeBehBeh** [comment]
Hello, I have the issue about my trajectory still seems  to drift. May I know how you solve it at the end?
