### ISSUE TITLE
Not publishing map

### ISSUE THREAD

**Issue by Semih67** [googlecartographer/cartographer_ros#1038]
I'm running google cartographer but it doesn't publish the map. I'm working with a laser scanner (rplidar). 

The rqt_graph looks like this: 
![rqt_graph](https://user-images.githubusercontent.com/33628476/46288892-a4be6c80-c587-11e8-9e70-c0a7d4c34a1a.png)

launch: 
![launch](https://user-images.githubusercontent.com/33628476/46288981-e6e7ae00-c587-11e8-8e51-c74402ffba8f.png)

urdf: 
![urdf](https://user-images.githubusercontent.com/33628476/46289003-f666f700-c587-11e8-97ee-d85e6c71dee4.png)

rqt: 
![rqt](https://user-images.githubusercontent.com/33628476/46289063-2dd5a380-c588-11e8-937c-e242a0452db3.png)

map: 
![map](https://user-images.githubusercontent.com/33628476/46289134-6f664e80-c588-11e8-90fd-f5c5e5ecd2f4.png)

lua: 
![lua](https://user-images.githubusercontent.com/33628476/46289261-d2f07c00-c588-11e8-84f0-0ef221ae0f92.png)

trajectory_2d: 
![trajectory2d](https://user-images.githubusercontent.com/33628476/46289281-e1d72e80-c588-11e8-9ab6-ff9af1340d45.png)

terminal:
![terminal](https://user-images.githubusercontent.com/33628476/46290339-dc2f1800-c58b-11e8-867a-5d324c9408e5.png)

I can see the topic map in the rostopic list:
/constraint_list
/joint_states
/landmark_poses_list
/map
/rosout
/rosout_agg
/scan
/scan_matched_points2
/submap_list
/tf
/tf_static
/trajectory_node_list

I don't know what exactly my problem is. I have these assumptions: 

-cartographer is not receiving any sensor data
-I don't know if I need a tf_listener. I didn't transform the sensor data from base_laser to base_link

**Comment by gaschler** [comment]
Please check the message type that your laser scanner publishes.
When you set num_laser_scans = 1, cartographer_ros subscribes to type "LaserScan" messages on the topic "scan".

**Comment by Semih67** [comment]
the topic "scan" has the message type "LaserScan"

**Comment by Semih67** [comment]
Ok, it's working now. After I inserted a world and map frame it worked.

**Comment by zchao9456** [comment]
Can you tell me how you did it? My question is the same as yours.

**Comment by zchao9456** [comment]
> Ok, it's working now. After I inserted a world and map frame it worked.

Can you tell me how you did it? My question is the same as yours.
