### ISSUE TITLE
Deutsches Museum - TSDF Tuning

### ISSUE THREAD

**Issue by alexmillane** [googlecartographer/cartographer_ros#1058]
Thanks @kdaun for the addition of TSDF mapping; this is great work and I'm excited to use it!

I was just wondering if someone had played around and found some good tunings for the Deutsches Mueseum dataset? With the default params in the scans appear to "slide around" quite a bit relative to the (sub)map.

**Comment by kdaun** [comment]
The TSDF is quite sensitive to the parameter configuration, here a [configuration for the Deutsches Museum dataset](https://drive.google.com/open?id=0BwEl1ypVvuqLSlRjWU5JazNLTThfY0toZ2F2S3ZaTVBTbGtB) and the resulting map:
![deutsches_museum_tsdf](https://user-images.githubusercontent.com/11328944/46852329-e73f3f00-cdfa-11e8-939b-18acf4ff26d0.png)
In my experience, in comparison to the Occupancy Grid pipeline, TSDF can improve the accuracy, the robustness to poor initial guesses and the convergence rate of the scan matching at the cost of a more expensive map updated and worse upper bounds for the branch-and-bound constraint search.
The airplane hall in the Deutsche Museum yields a reduced accuracy, as the TSDF is more sensitive to the strongly moving point observations when scanning the wings.

I'm still working on the TSDF approach and looking forward to hear about your results.

**Comment by alexmillane** [comment]
Cheers for this! Works great! Looking forward to seeing how things progress. I'll let you know if I manage to come up with anything interesting.

Again, great work and thanks for the help.
