### ISSUE TITLE
High CPU usage of Cartographer

### ISSUE THREAD

**Issue by RodolphePerrin** [googlecartographer/cartographer_ros#1073]
Hello, 

We have recently started using Cartographer in our project for mapping and localization. So far, our results have been mostly great in our indoor environment. However, we noticed a large latency (with high CPU usage from the Cartographer node) when mapping sometimes. 

We are using a Hokuyo Lidar (UST-20LX) at level fixed connected to a NuC with 8 cores (PC with 4-core / 8-thread processor (Intel Core i7-8650U) and 16 GB RAM). 

Our current config file is the following: 

`
include "map_builder.lua"
include "trajectory_builder.lua"

options = {
  map_builder = MAP_BUILDER,
  trajectory_builder = TRAJECTORY_BUILDER,
  map_frame = "map",
  tracking_frame = "laser",
  published_frame = "base_footprint",
  odom_frame = "odom",
  provide_odom_frame = true,
  publish_frame_projected_to_2d = false,
  use_odometry = false,
  use_nav_sat = false,
  use_landmarks = false,
  num_laser_scans = 1,
  num_multi_echo_laser_scans = 0,
  num_subdivisions_per_laser_scan = 10,
  num_point_clouds = 0,
  lookup_transform_timeout_sec = 0.2,
  submap_publish_period_sec = 0.3,
  pose_publish_period_sec = 5e-3,
  trajectory_publish_period_sec = 30e-3,
  rangefinder_sampling_ratio = 1.,
  odometry_sampling_ratio = 1.,
  fixed_frame_pose_sampling_ratio = 1.,
  imu_sampling_ratio = 1.,
  landmarks_sampling_ratio = 1.,
}

MAP_BUILDER.use_trajectory_builder_2d = true
TRAJECTORY_BUILDER_2D.ceres_scan_matcher.translation_weight = 1.

TRAJECTORY_BUILDER_2D.num_accumulated_range_data = 10
TRAJECTORY_BUILDER_2D.submaps.num_range_data = 35
TRAJECTORY_BUILDER_2D.max_range = 20.
TRAJECTORY_BUILDER_2D.min_z = -0.1
TRAJECTORY_BUILDER_2D.max_z = 0.1
TRAJECTORY_BUILDER_2D.min_range = 0.
TRAJECTORY_BUILDER_2D.missing_data_ray_length = 1.
TRAJECTORY_BUILDER_2D.use_imu_data = false
TRAJECTORY_BUILDER_2D.use_online_correlative_scan_matching = false
TRAJECTORY_BUILDER_2D.real_time_correlative_scan_matcher.linear_search_window = 0.1
TRAJECTORY_BUILDER_2D.real_time_correlative_scan_matcher.translation_delta_cost_weight = 10.
TRAJECTORY_BUILDER_2D.real_time_correlative_scan_matcher.rotation_delta_cost_weight = 1e-1

return options`

We are currently not using any IMU or Odometry in Cartographer, just using laser scan matching. We noticed that the parameter  `TRAJECTORY_BUILDER_2D.use_online_correlative_scan_matching = false` has a big influence on the system. 

When set to false, we get more localization issues but lower CPU usage. Localization issues seem to be resolved when set back to true. However, the CPU usage is then peaking sometimes, slowing the entire system which makes it impossible for us to test. 

We tested a bit to tune the system for low latency as described on the Cartographer website but so far haven’t been able to solve that issue. Have someone encountered a similar issue ? Does Cartographer work better ( efficient CPU usage and mapping) with the support of an IMU/odom ?

Thanks.

**Comment by cschuet** [comment]
Giving cartographer access to odometer and imu measurements will allow us to generate much better pose estimates before scan matching. If the data is reasonable you will most definitely be able to turn off the correlative Scan matcher.
