### ISSUE TITLE
finish trajectory error

### ISSUE THREAD

**Issue by carl1218** [googlecartographer/cartographer_ros#1078]
hi,
when i runned:rosservice call /finish_trajectory 0 ，The following errors will occur.
```
ERROR: Unable to load type [cartographer_ros_msgs/FinishTrajectory].
have you typed 'make' in [cartographer_ros_msgs]?
```

**Comment by MichaelGrupp** [comment]
`rosservice` (written in Python) dynamically loads the corresponding class for a message type (here: "FinishTrajectory". When you build `cartographer_ros_msgs`, code for such classes is automatically generated in your workspace from the `.msg` files.

Probably one of the two (or both) things can help:
* build `cartographer_ros_msgs`
* source the ROS environment

**Comment by carl1218** [comment]
@MichaelGrupp ，
Thank you.
