### ISSUE TITLE
IDE used to debug cartographer

### ISSUE THREAD

**Issue by zldodo** [googlecartographer/cartographer_ros#1094]
Hi,

Very appreciate your awesome work on Cartographer!

I have been finding a useful IDE for debuging Carto algorithm. I've touched CLION, Kdevelop, GDB etc. 
But these IDEs seemly do not  work well with Carto. Also, I'm not sure if I've configured them correctly. 

Could you give me some advice or hints about how to debug on Carto ? In which way you prefer to do debuging? with Prinf/ROS_INFO?

**Comment by ojura** [comment]
I am using CLion, it works very well. Unfortunately, you can't use it with a regular Catkin workspace which builds stuff in isolation.

Check out https://github.com/larics/cartographer_superbuild, it might be exactly what you need.

**Comment by zldodo** [comment]
Firstly, thanks  a lot for you help. I've already taken steps following with https://github.com/larics/cartographer_superbuild,  but I still cannot make it work successfully and some errors occurred.

After completing **Building with CMake** , I imported **cartographer_superbuild** into Clion and changed the CMake build type to RelWithDebInfo. Then, I opened Run -> Edit Configurations, found "cartographer_supperbuild ", instead of "cartographer_node" you said. Have I done something wrong? 

Besides, I also tried to build this project with CLion, using Run->Build. Unfortunately, Here is what I got:
> /home/zl23/clion-2018.2.5/bin/cmake/linux/bin/cmake --build /home/zl23/cartographer_superbuild/cmake-build-relwithdebinfo --target cartographer_superbuild -- -j 2
[  0%] Building CXX object CMakeFiles/cartographer_superbuild.dir/build/cartographer/cartographer/ground_truth/proto/relations.pb.cc.o
[  0%] Building CXX object CMakeFiles/cartographer_superbuild.dir/build/cartographer/cartographer/common/proto/ceres_solver_options.pb.cc.o
/home/zl23/cartographer_superbuild/build/cartographer/cartographer/common/proto/ceres_solver_options.pb.cc:5:63: fatal error: cartographer/common/proto/ceres_solver_options.pb.h: No such file or directory
/home/zl23/cartographer_superbuild/build/cartographer/cartographer/ground_truth/proto/relations.pb.cc:5:58: fatal error: cartographer/ground_truth/proto/relations.pb.h: No such file or directory
compilation terminated.
compilation terminated.
CMakeFiles/cartographer_superbuild.dir/build.make:62: recipe for target 'CMakeFiles/cartographer_superbuild.dir/build/cartographer/cartographer/common/proto/ceres_solver_options.pb.cc.o' failed
make[3]: *** [CMakeFiles/cartographer_superbuild.dir/build/cartographer/cartographer/common/proto/ceres_solver_options.pb.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
CMakeFiles/cartographer_superbuild.dir/build.make:75: recipe for target 'CMakeFiles/cartographer_superbuild.dir/build/cartographer/cartographer/ground_truth/proto/relations.pb.cc.o' failed
make[3]: *** [CMakeFiles/cartographer_superbuild.dir/build/cartographer/cartographer/ground_truth/proto/relations.pb.cc.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/cartographer_superbuild.dir/all' failed
make[2]: *** [CMakeFiles/cartographer_superbuild.dir/all] Error 2
CMakeFiles/Makefile2:84: recipe for target 'CMakeFiles/cartographer_superbuild.dir/rule' failed
make[1]: *** [CMakeFiles/cartographer_superbuild.dir/rule] Error 2
Makefile:118: recipe for target 'cartographer_superbuild' failed
make: *** [cartographer_superbuild] Error 2

**Is this kind of error related to "Protobuf"?** When I builded Carto with the official way that is "catkin_make_isolated", there is  a folder named "Protobuf" under "catkin_ws/", but above "/src".

**Comment by ojura** [comment]
The build folder you created is not used by CLion.

If you are on Ubuntu 16.04 and have to specify location of Protobuf 3 to CMake (by adding it to `CMAKE_PREFIX_PATH` or by setting `Protobuf_DIR`), you have to do the same inside CLion (the same options tab where you changed to build type to `RelWithDebInfo`).

I have not used this with Ubuntu 16.04 since Cartographer started requiring Protobuf 3 so there might be some other CMake thing you need to do. I highly recommend upgrading to Ubuntu 18.04.

**Comment by zldodo** [comment]
I checked the installation position of Protobuf 3 

> zl23@csvw:~/cartographer_superbuild/$ which protoc
/usr/local/bin/protoc

and the version of it

> zl23@csvw:~/cartographer_superbuild/build$ protoc --version
libprotoc 3.4.0

To my knowledge, there is no need to specify location of Protobuf 3 to CMake (by adding it to CMAKE_PREFIX_PATH or by setting Protobuf_DIR), since it has been installed under "/usr/local". Moreover, when it is built with CMake in terimal, "mkdir build, cd build, cmake ../, make -j8", everything goes well. Then, I deleted the  build folder created by CMake. However, once this project was imported into CLion, something wrong happened as listed above. Even though I added "-DCMAEK_PREFIX_PATH=${CMAEK_PREFIX_PATH}:/usr/local/bin/protoc " inside CLion(Cmake options), same error existed. 

Besides, I also imported this project into **Kdevelop** and changed the build type into RelWithDebInfo. When I clicked the build button, here is what I got:

> /home/zl23/cartographer_superbuild/build> /usr/bin/cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=RelWithDebInfo /home/zl23/cartographer_superbuild/
-- Build type: RelWithDebInfo
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   iostreams
--   regex
-- Found installed version of Eigen: /usr/lib/cmake/eigen3
-- Found required Ceres dependency: Eigen version 3.2.92 in /usr/include/eigen3
-- Found required Ceres dependency: glog
-- Found required Ceres dependency: gflags
-- Found Ceres version: 1.14.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, OpenMP, Multithreading]
CMake Error at cartographer_ros/cartographer_ros_msgs/CMakeLists.txt:24 (find_package):
  By not providing "Findcatkin.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "catkin", but
  CMake did not find one.

  Could not find a package configuration file provided by "catkin" with any
  of the following names:

    catkinConfig.cmake
    catkin-config.cmake

  Add the installation prefix of "catkin" to CMAKE_PREFIX_PATH or set
  "catkin_DIR" to a directory containing one of the above files.  If "catkin"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/zl23/cartographer_superbuild/build/CMakeFiles/CMakeOutput.log".
See also "/home/zl23/cartographer_superbuild/build/CMakeFiles/CMakeError.log".
*** Failure: Exit code 1 ***

This error was different from the previous one, but I still have no idea to deal with this. I've already echo "source /opt/ros/kinetic/setup.bash" into .bashrc.

I am on Ubuntu 16.04 now. Do you think I should use CLion in Ubuntu18.04 to test this project again?

**Comment by zldodo** [comment]
Thanks a lot for your helpful answer. After adding `/opt/ros/...` into Kdevelop inlcudes, the build process worked normally. Additionally, I also added `/usr/include/eigen3`, which is referenced by this project. 

Back to CLion again, I found the reason for those errors, for example:

> /home/zl23/clion-2018.2.5/bin/cmake/linux/bin/cmake --build /home/zl23/cartographer_superbuild3/cmake-build-relwithdebinfo --target all -- -j 2
...
...
/home/zl23/cartographer_superbuild3/cartographer/cartographer/mapping/id.h:33:54: fatal error: cartographer/mapping/proto/pose_graph.pb.h: No such file or directory

In this example, `cartographer/mapping/proto/pose_graph.pb.h` was not found, but `cartographer/mapping/proto/pose_graph.proto` existed.   Then, I  looked up  `pose_graph.pb.h` in the folders with CMake and Kdevelop cases. In fact, I found `pose_graph.pb.h` lies in in generated folder, eg. 

> zl23@csvw:~/cartographer_superbuild/build$ locate pose_graph.pb.h 
/home/zl23/cartographer_superbuild/build/cartographer/cartographer/mapping/proto/pose_graph.pb.h
/home/zl23/cartographer_superbuild2/build/cartographer/cartographer/mapping/proto/pose_graph.pb.h

It seems that `pose_graph.pb.h` is firstly generated by`pose_graph.proto` and then referenced by others functions. The problem is, after I imported this project into CLion,  this kind of files were not created and thus not found in the build process. What do you think of this?

**Comment by ojura** [comment]
You should not have had to add `/usr/include/eigen3`, that sounds very strange. I don‘t know why Protobuf would fail to build the headers when you are building from CLion. My suggestion would be to start with a fresh install of Ubuntu 18.04, or 16.04 with Protobuf installed to /home or /opt.

**Comment by ojura** [comment]
I am glad it works for you now. Also, you can use the stuff from the `cmake-build-...` directory (like launch files)  just like you would from a regular Catkin workspace by running `source cmake-build-.../devel/setup.bash`.
