### ISSUE TITLE
How to used two 2d lidars in cartographer 3d

### ISSUE THREAD

**Issue by carl1218** [googlecartographer/cartographer_ros#1133]
Hi,
 I used two 2d lidars (one 40hz,one 10hz) in cartographer  3d, I kept two lidars still and not moving.But the map data is very confusing,and Laser data drift constantly,look like this:
![6876e765a5c9d79b3be5f35363e7c4fc](https://user-images.githubusercontent.com/17962046/50285482-44104300-0497-11e9-8491-fc0ca3e5eaa8.png)

and it will be error about 20s later,look like this:
![7l7 aye tet n7 mu 3c l](https://user-images.githubusercontent.com/17962046/50285728-17a8f680-0498-11e9-8534-9b3334c1e0fb.png)

how can i set in cartographer 3d? Thank you.

this is my launch:
https://drive.google.com/file/d/1n6UG_JsHYpDKqr1Ft-0-Ie2DjJOaxdLG/view
this is lua:
https://drive.google.com/file/d/1h-2d1RuM2iTCfG2070rtKOPbKYF0bA5Z/view?usp=sharing
this is urdf:
https://drive.google.com/file/d/1_yQsX8TiHp5DPmlYcHZdFTSXYZ9Fioyd/view?usp=sharing
this is rosbag:
https://drive.google.com/file/d/1lBeqG_CRBL9U-tYQntL6jwqSIqq1GPeI/view?usp=sharing

**Comment by rdesc** [comment]
how are your two 2d lidars setup exactly?
