### ISSUE TITLE
Height problem when using 3d mapping

### ISSUE THREAD

**Issue by smail1229** [googlecartographer/cartographer_ros#1158]
Hello, 
I am tring to using cartographer 3d mapping with 16-line lidar,  IMU, gps and odometry, and running it successfully.
But when I tried to build a map around a 100m*30m building, the z value of the robot's position not correct (when the robot returned to starting point, z value is **-4**) and make cartographer failed to make a loop closure.
![default](https://user-images.githubusercontent.com/11934648/51162265-8da25100-18d0-11e9-9928-d8032d6189e4.png)
![default](https://user-images.githubusercontent.com/11934648/51162276-9561f580-18d0-11e9-9e74-de08f3be3f31.png)

Here is my lua file:

`include "map_builder.lua"
include "trajectory_builder.lua"

options = {
  map_builder = MAP_BUILDER,
  trajectory_builder = TRAJECTORY_BUILDER,
  map_frame = "map",
  tracking_frame = "base_footprint",
  published_frame = "odom",
  odom_frame = "odom",
  provide_odom_frame = false,
  use_odometry = false,
  use_nav_sat = true,
  use_landmarks = false,
  publish_frame_projected_to_2d = false,
  landmarks_sampling_ratio = 1.,
  num_laser_scans = 1,
  num_multi_echo_laser_scans = 0,
  num_subdivisions_per_laser_scan = 1,
  num_point_clouds = 0,
  lookup_transform_timeout_sec = 0.2,
  submap_publish_period_sec = 0.3,
  pose_publish_period_sec = 5e-3,
  trajectory_publish_period_sec = 30e-3,
  rangefinder_sampling_ratio = 1.,
  odometry_sampling_ratio = 1.,
  fixed_frame_pose_sampling_ratio = 1.,
  imu_sampling_ratio = 1.,
}

MAP_BUILDER.use_trajectory_builder_3d = true

MAP_BUILDER.num_background_threads = 7

POSE_GRAPH.optimization_problem.huber_scale = 1e1
POSE_GRAPH.optimization_problem.acceleration_weight = 1e1
POSE_GRAPH.optimization_problem.rotation_weight = 3e5
POSE_GRAPH.optimization_problem.ceres_solver_options.max_num_iterations = 50

POSE_GRAPH.optimize_every_n_nodes  = 40
POSE_GRAPH.optimization_problem.odometry_translation_weight = 1e5  
POSE_GRAPH.optimization_problem.odometry_rotation_weight = 1e5

TRAJECTORY_BUILDER_3D.low_resolution_adaptive_voxel_filter.max_range = 30
TRAJECTORY_BUILDER_3D.low_resolution_adaptive_voxel_filter.min_num_points = 200
TRAJECTORY_BUILDER_3D.high_resolution_adaptive_voxel_filter.max_range = 30
TRAJECTORY_BUILDER_3D.high_resolution_adaptive_voxel_filter.min_num_points = 150
TRAJECTORY_BUILDER_3D.submaps.high_resolution_max_range = 30.
TRAJECTORY_BUILDER_3D.submaps.high_resolution = 0.1
TRAJECTORY_BUILDER_3D.submaps.low_resolution = 0.45
TRAJECTORY_BUILDER_3D.max_range = 30
TRAJECTORY_BUILDER_3D.min_range = 0.25

options.use_odometry = true
options.num_laser_scans = 0
options.num_multi_echo_laser_scans = 0
options.num_point_clouds = 1

return options`

Is it my sensor data's problem?
May I solve this problem by change some params?

Thanks for any help or advice.

**Comment by gaschler** [comment]
This is almost always the result of a rotation error in the static transform between lidar and IMU that you provide.

You can increase the search radius, let Cartographer find it, and enable logs of the calibration results, and Cartographer will print a correction (assuming it was able to loop-close).

**Comment by smail1229** [comment]
> lidar and IMU that you provide.

Thanks for reply
I wonder if cartographer will use the static transform of IMU, I only find the use of linear_acceleration and angular_velocity in these code.

**Comment by ojura** [comment]
Also have a look at https://github.com/googlecartographer/cartographer_ros/pull/1025 (@gaschler review ping? :-) ). It enables easy use of the IMU correction quaternion outputted by Cartographer without having to modify your transforms.

**Comment by Duke-Allen** [comment]
@smail1229 
Hi, I am using 16-lines lidar and IMU to run the cartographer. I have a question about the `tracking_frame` in the lua file. It says that the tracking_frame should be the same frame as the IMU at the [document](https://google-cartographer-ros.readthedocs.io/en/latest/configuration.html#lua-configuration-reference-documentation). Is it must be set the same frame as the IMU?

**Comment by smail1229** [comment]
@Duke-Allen
Hi，about tracking frame as I known, if your imu's direction is always lock to the same direction as your robot, you can just set the tf of imu to base_footprint as (0,0,0)(0,0,0), then you can set base_footprint as tracking_frame.

Otherwise tracking_frame must be imu frame or cartographer won't work.

**Comment by Duke-Allen** [comment]
@smail1229 
Thanks for your reply. I am sorry to reply you so late.
 I am new to cartographer. Could you tell me how to set the tf of imu to base_footprint as (0,0,0)? I also have a problem. Do you know the cartographer could build 3D map with a 16-lines lidar and a 6dor IMU?
