### ISSUE TITLE
Cartographer build 2D map error

### ISSUE THREAD

**Issue by Duke-Allen** [googlecartographer/cartographer_ros#1167]
Hi, I'm getting the data in real time by cartographer with a 16-line lidar and IMU, but it build map error.

[ WARN] [1547981846.907645880]: W0120 18:57:26.000000 22251 tf_bridge.cc:52] "rslidar" passed to lookupTransform argument target_frame does not exist. 
[ WARN] [1547981847.108506027]: W0120 18:57:27.000000 22251 tf_bridge.cc:52] "rslidar" passed to lookupTransform argument target_frame does not exist. 
[ WARN] [1547981847.309533083]: W0120 18:57:27.000000 22251 tf_bridge.cc:52] "rslidar" passed to lookupTransform argument target_frame does not exist. 
[ WARN] [1547981847.510363532]: W0120 18:57:27.000000 22251 tf_bridge.cc:52] "rslidar" passed to lookupTransform argument target_frame does not exist. 
[ WARN] [1547981847.711192669]: W0120 18:57:27.000000 22251 tf_bridge.cc:52] "rslidar" passed to lookupTransform argument target_frame does not exist. 
[ WARN] [1547981847.911937423]: W0120 18:57:27.000000 22251 tf_bridge.cc:52] "rslidar" passed to lookupTransform argument target_frame does not exist. 
[ WARN] [1547981848.112949723]: W0120 18:57:28.000000 22251 tf_bridge.cc:52] "rslidar" passed to lookupTransform argument target_frame does not exist.

[rslidar.launch file:](https://github.com/Duke-Allen/cartographer-configuration.git)
<launch>
  <param name="/use_sim_time" value="false" />

  
  <node name="cartographer_node" pkg="cartographer_ros"
      type="cartographer_node" args="
          -configuration_directory
              $(find cartographer_ros)/configuration_files
          -configuration_basename rslidar_scan_imu.lua"
      output="screen">
      <remap from="/scan" to="scan" />

  </node>

  <node name="cartographer_occupancy_grid_node" pkg="cartographer_ros"
      type="cartographer_occupancy_grid_node" args="-resolution 0.05" />

</launch>

[rslidar_scan_imu.lua file:](https://github.com/Duke-Allen/cartographer-configuration.git)
include "map_builder.lua"
include "trajectory_builder.lua"
options = {
 map_builder = MAP_BUILDER,
 trajectory_builder = TRAJECTORY_BUILDER,
 map_frame = "map",
 tracking_frame = "rslidar",
 published_frame = "rslidar",
 odom_frame = "odom",
 provide_odom_frame = false,
 publish_frame_projected_to_2d = false,
 use_odometry = false,
 use_nav_sat = false,
 use_landmarks = false,
 num_laser_scans = 1,
 num_multi_echo_laser_scans = 0,
 num_subdivisions_per_laser_scan = 1,
 num_point_clouds = 0,
 lookup_transform_timeout_sec = 0.2,
 submap_publish_period_sec = 0.3,
 pose_publish_period_sec = 5e-3,
 trajectory_publish_period_sec = 30e-3,
 rangefinder_sampling_ratio = 1.,
 odometry_sampling_ratio = 1.,
 fixed_frame_pose_sampling_ratio = 1.,
 imu_sampling_ratio = 1.,
 landmarks_sampling_ratio = 1.,
}

MAP_BUILDER.use_trajectory_builder_2d = true

TRAJECTORY_BUILDER_2D.submaps.num_range_data = 35
TRAJECTORY_BUILDER_2D.min_range = 0.2
TRAJECTORY_BUILDER_2D.max_range = 150.
TRAJECTORY_BUILDER_2D.missing_data_ray_length = 5.
TRAJECTORY_BUILDER_2D.use_imu_data = true
TRAJECTORY_BUILDER_2D.use_online_correlative_scan_matching = true
TRAJECTORY_BUILDER_2D.real_time_correlative_scan_matcher.linear_search_window = 0.1
TRAJECTORY_BUILDER_2D.real_time_correlative_scan_matcher.translation_delta_cost_weight = 10.
TRAJECTORY_BUILDER_2D.real_time_correlative_scan_matcher.rotation_delta_cost_weight = 1e-1

POSE_GRAPH.optimization_problem.huber_scale = 1e2
POSE_GRAPH.optimize_every_n_nodes = 35
POSE_GRAPH.constraint_builder.min_score = 0.65

return options

The IMU data is constant. Please help and guide me, thank you.

**Comment by numb0824** [comment]
hi，i meet the same question，could help me what to do to solve it？
