### ISSUE TITLE
Loop closure

### ISSUE THREAD

**Issue by fprott** [googlecartographer/cartographer_ros#1220]
Hello,

I have a rather simple question that I do not seem to find anywhere in the documentation: how to find out that loop-closure (reliably) happened? 
In other words, if I have a small robot traveling in a circle of a few meters radius, how does cartographer tell me that the circle just has been closed?
Is there a flag or a topic or anything I am missing? If not, what is the easiest way to extract the information?

**Comment by gaschler** [comment]
To be sure there is a recent loop closure constraint, you can query `PoseGraphInterface::constraints()`, loop over all constraints and check if there is a recent one of type `INTER` that spans some time.

A simpler solution is to subscribe to the global slam callback `GlobalSlamOptimizationCallback` by setting `PoseGraphInterface::SetGlobalSlamOptimizationCallback`. This will call you back after Cartographer has searched for loop closures. It does not tell you if loop closures were found, it mostly tells you if the background loop closure search is keeping up or falls behind.

**Comment by fprott** [comment]
Many thanks. That is very helpful. Also thanks for the quick answer.
Is there a reason to not flag loop closure? Because I find it quite helpful for every robot that is exploring.
