### ISSUE TITLE
Running cartographer_ros with custom messages types

### ISSUE THREAD

**Issue by bbidault** [googlecartographer/cartographer_ros#123]
Hello. I am trying to run cartographer_ros with custom messages types and I would like to know which file I should work on and modify so that cartographer runs properly.

My messages are structured like follow,
   ps_platform_motion_msg (imu messages)
ps_msg_header 	header
ps_sensor_descriptor 	sensor_descriptor
ps_timestamp 	timestamp
ps_native_timestamp 	native_timestamp
double 	position [3]
double 	orientation [4]
double 	rotation_rate [3]
double 	velocity [3]
double 	acceleration [3]
double 	heading
double 	latitude
double 	longitude
double 	altitude

   ps_lidar_points_msg (3d lidar pointcloud messages)
 ps_msg_header 	header
ps_sensor_descriptor 	sensor_descriptor
ps_timestamp 	start_timestamp
ps_timestamp 	end_timestamp
ps_native_timestamp 	native_start_timestamp
sequence< ps_lidar_point > 	points

   ps_lidar_point
float 	position [3]
octet 	intensity

Thank you and keep up the good work.
Boris

**Comment by damonkohler** [comment]
You're best off converting your messages to the standard ROS messages. If you're concerned about the copying of data, you can modify node_main.cc and sensor_bridge.cc to work over your custom data types. Please reopen if you need more information.
