### ISSUE TITLE
Obtaining Quality of SLAM

### ISSUE THREAD

**Issue by mojovski** [googlecartographer/cartographer_ros#1269]
I would like to estimate the quality of the SLAM solution provided by cartographer. 
It could be cor example some metric, indicating that there is 99% no better solution obtainable using global localization/ loop closing.

Is there something one could extract out of cartographer and publish as a topic/rosparam?

Thanks!

**Comment by MichaelGrupp** [comment]
https://github.com/googlecartographer/cartographer_ros/issues/1258

**Comment by mojovski** [comment]
Hehe, just in time! :) Thanks!
