### ISSUE TITLE
I can't convert when I execute commands

### ISSUE THREAD

**Issue by ytgcljj** [googlecartographer/cartographer_ros#1289]
nuc16@nuc16:~/111$ rosrun cartographer_ros cartographer_pbstream_to_ros_map -pbstream_filename=/home/nuc16/catkin_ws/install_isolated/share/cartographer_ros/maps/ros.pbstream -map_filestem=/home/nuc16/111/11
I0516 11:13:27.143431 22153 pbstream_to_ros_map_main.cc:52] Loading submap slices from serialized data.
段错误

**Comment by gaschler** [comment]
Please ask as a question and add detail. The logs look normal to me.

**Comment by ytgcljj** [comment]
Sorry, I can't see the log, my Ubuntu 16.04.5, I found a problem. If you save the pbstream file as root, you can't convert it. If you save the pbstream file as nuc16, you can convert it. Please explain.
