### ISSUE TITLE
How to integrate .ply file from cartographer to octomap_mapping

### ISSUE THREAD

**Issue by shrijan00** [googlecartographer/cartographer_ros#1295]
Hi, I have point cloud in .ply format from Cartographer and I want to use this for generating the Octomap in Rviz using this octomap_mapping [Here](http://wiki.ros.org/octomap_mapping). Is it possible to do so or do I have to use separate viewer for generating octomap or writing a separate node to read the .ply file and then publish as pointcloud2 type can also be an option?

**Comment by ojura** [comment]
I think that this question is better suited to the Octomap repository or mailing list. As far as Cartographer is concerned, it has outputted a .ply cloud, and how you use it further is related to Octomap.
