### ISSUE TITLE
Failed to process package 'cartographer_ros'

### ISSUE THREAD

**Issue by huangshuqing** [googlecartographer/cartographer_ros#1301]
I use protobuf with the version 3.4.1 and cmake with the version 3.2.2.2. I download master of both cartographer and cartographer ros. when I build and install: "catkin_make_isolated --install --use-ninja",meet the errors as fllows:

ninja: build stopped: subcommand failed.
<== Failed to process package 'cartographer_ros': 
  Command '['/home/chiebot/test_ws/install_isolated/env.sh', 'ninja', '-j8', '-l8']' returned non-zero exit status 1

Reproduce this error by running:
==> cd /home/chiebot/test_ws/build_isolated/cartographer_ros && /home/chiebot/test_ws/install_isolated/env.sh ninja -j8 -l8

**Comment by Srichitra-S** [comment]
How did you resolve this? @huangshuqing
