### ISSUE TITLE
Error building cartographer_rviz after latest update

### ISSUE THREAD

**Issue by masterhui** [googlecartographer/cartographer_ros#138]
Hi
I updated cartographer_ros from a previous version (Oct 6, commit 1418902493115cad90d6ee93877c5a602a78614f) to the most up-to-date one (Oct 21, commit 20487028ed36c558336a873860cfe90340e8662f). While building completed without errors previously, I now get the following error:

> Errors     << cartographer_rviz:make /home/ros/catkin_ws/logs/cartographer_rviz/build.make.005.log                                      
In file included from /home/ros/catkin_ws/build/cartographer_rviz/cartographer_rviz/../../../src/overlay/cartographer_ros/cartographer_rv
iz/cartographer_rviz/drawable_submap.h:35:0,
                 from /home/ros/catkin_ws/build/cartographer_rviz/cartographer_rviz/moc_drawable_submap.cpp:9,
                 from /home/ros/catkin_ws/build/cartographer_rviz/cartographer_rviz/drawable_submap_automoc.cpp:2:
/opt/ros/kinetic/include/rviz/display_context.h:34:19: fatal error: QObject: No such file or directory
compilation terminated.
make[2]: *** [cartographer_rviz/CMakeFiles/drawable_submap.dir/drawable_submap_automoc.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/ros/catkin_ws/src/overlay/cartographer_ros/cartographer_rviz/cartographer_rviz/drawable_submap.h:35:0,
                 from /home/ros/catkin_ws/src/overlay/cartographer_ros/cartographer_rviz/cartographer_rviz/drawable_submap.cc:17:
/opt/ros/kinetic/include/rviz/display_context.h:34:19: fatal error: QObject: No such file or directory
compilation terminated.
make[2]: *** [cartographer_rviz/CMakeFiles/drawable_submap.dir/drawable_submap.cc.o] Error 1
make[1]: *** [cartographer_rviz/CMakeFiles/drawable_submap.dir/all] Error 2
make: *** [all] Error 2

My setup:
Ubuntu 16.04
ROS Kinetic
x86_64

I do realize that you mention ROS Kinetic not being fully supported by cartographer_ros, however as there were no build errors previously and now there are, I thought I'd report this anyway.

Regards

**Comment by SirVer** [comment]
Could you bisect which was the breaking build in `cartographer_ros`?

**Comment by masterhui** [comment]
No, sorry, I updated straight from 1418902493115cad90d6ee93877c5a602a78614f to 20487028ed36c558336a873860cfe90340e8662f.

**Comment by wuhaixing** [comment]
I meet the error too:

> /opt/ros/kinetic/include/rviz/display_context.h:34:19: fatal error: QObject:No such file or directory
compilation terminated.

**Comment by SirVer** [comment]
@wuhaixing Can you point us to the breaking commit?

**Comment by spyke555** [comment]
I can get it to build fine up until the Oct12th updates. Using cartographer commit 8f64860 and cartographer_ros 0e8d219 works fine. Using cartographer_ros be7ce01 breaks the build for me with the same error as described in the OP...

**Comment by jsgaobiao** [comment]
I meet the error too. :(

**Comment by spyke555** [comment]
The QT version is also what I am suspecting based on what I've been able to research. I have installed QT4 on my system, but likely need to instruct the build scripts to use that instead of QT5...

**Comment by SirVer** [comment]
I was able to reproduce this with a fresh docker image and was able to fix. Please verify and reopen if it is still a problem.

**Comment by spyke555** [comment]
Confirming problem resolved, thanks!

**Comment by masterhui** [comment]
I can also confirm that this has been fixed. Well done, cheers!
