### ISSUE TITLE
about the type of data

### ISSUE THREAD

**Issue by Needrom** [googlecartographer/cartographer_ros#140]
I just find a way to change the data to laserscan with the pkg of depthimage_to_laserscan.but no way I can find to change the data from depthimage to the MulitEchoLaserScan . if any easy way to change it to the type I want ,please tell me ~~

**Comment by SirVer** [comment]
You can use `laser_scan` data type for Cartographer by setting `use_horizontal_multi_echo_laser` to false and set `use_horizontal_laser` to true, [see here](https://github.com/googlecartographer/cartographer_ros/blob/master/cartographer_ros/configuration_files/backpack_2d.lua#L32).

Closing, please reopen if there are questions remaining.

**Comment by Needrom** [comment]
thanks ！！！
