### ISSUE TITLE
Source of initial guess for the pose extrapolator if no odometry and IMU data is provided?

### ISSUE THREAD

**Issue by gsh89** [googlecartographer/cartographer_ros#1429]
The documentation for Cartographer ROS says the following:
 ''Local SLAM inserts a new scan into its current submap construction by scan matching using an initial guess from the pose extrapolator. The idea behind the pose extrapolator is to use sensor data of other sensors besides the range finder to predict where the next scan should be inserted into the submap.''

My question is the following 
If I disable use_odometry and use_imu_data, what does the extrapolator base its initial guess on ?
FYI - My robot has a laser scanner, an IMU and has wheel based odometry.

**Comment by ojura** [comment]
I believe the speed is simply estimated in `PoseExtrapolator` as the difference of the last couple of positions divided by time.

**Comment by gsh89** [comment]
Thanks @ojura .  Would you also happen to know if using odometry and IMU as data sources, act only as initial guess to the scan matcher or do they affect the final pose estimate too and how can each scenario be configured ?

**Comment by ojura** [comment]
The odometry and the IMU data is used to unwarp the scan (e.g. account for motion during the lidar sweep) prior to scan matching. There is nothing to configure except the use imu data/odometry settings you mentioned. Perhaps the translation and rotation weights of the scan matcher, which control how much the prior is trusted.
