### ISSUE TITLE
IMU Accel and Gyro coordinate frames

### ISSUE THREAD

**Issue by desmosedic** [googlecartographer/cartographer_ros#160]
I am using a VLP 16 Puck to input data to the Horizontal Lidar input. Everything seems OK but I think I still don't have the coordinate frames or the units right. Can anyone tell me the Accelerometer and Gyro coordinate frames and the units of measurement? Is there any relevant documentation I can look up?

**Comment by damonkohler** [comment]
The coordinate frames are configured in your URDF. I suggest reaching out to http://answers.ros.org/ for help with that.
