### ISSUE TITLE
how to make the size of occupancy grid map lager?

### ISSUE THREAD

**Issue by oya123** [googlecartographer/cartographer_ros#164]
I'm now using kobuki and rplidar to build map, and I could get occupancy grid map from cartographer node. But I want to use the map to do other work like navigation that the more unknown space in map is needed.
Is there any method could help me to solve this problem?
I just find the map size information in cartographer_ros/cartographer_ros/cartographer_ros/occupancy_grid.cc line 59-60.
`occupancy_grid->info.width = cell_limits.num_y_cells;
occupancy_grid->info.height = cell_limits.num_x_cells;`
It couldn't help me that changing the info.width and info.height because it destroy the map.

**Comment by SirVer** [comment]
First, you should not use this code path as it is super slow. Building and publishing the occupancy grid is only to get people jump started with cartographer. Once you settle on using it, you should work over the submap representation as it is far more efficient.

That said, we do not support padding the occupancy grid - and have no intention of doing so. We always publish a occupancy grid containing exactly the cells we know about. If you want a padded occupancy grid, you have to write a small node, that listens to the one from cartographer, pads it and republishes it on a different topic.
