### ISSUE TITLE
Cartographer & Velodyne Lidar 

### ISSUE THREAD

**Issue by alvarezmdavid** [googlecartographer/cartographer_ros#165]
Hi! i'm new working with slam and acquisition im in an internship working with a VLP16, also new in ROS, so i'm sorry is this is a dumb question, i want to know if theres a way to do the mapping by acquiring the data from the velodyne packets (velodyne_pointcloud), and if there is a way, how can i do it? 

I can see that you work with diferent types of topics, nodes and msgs, can i modify something to get this working with my Velodyne?

Thank You

**Comment by damonkohler** [comment]
The [backpack_3d configuration](https://google-cartographer-ros.readthedocs.io/en/latest/#running-the-demos) is set up for consuming Velodyne data. You'll need to set up the driver and plumbing yourself though. For help with that, I suggest reaching out on http://answers.ros.org/.
