### ISSUE TITLE
how to limit memory in practical envoriment?

### ISSUE THREAD

**Issue by tom8382** [googlecartographer/cartographer_ros#167]
i guess, if i'm not wrong, carto will store every Effective laser scan and every some scans it add a submap. is this increase along with time going on? is this any mechanism such as,  after loop closure we need merge some submaps and scans?

**Comment by damonkohler** [comment]
There is no mechanism to reduce the memory footprint in the way you describe. We consider that to be part of "lifelong mapping," which is something we'd like to add but haven't yet.

That said, on a modest PC, we've mapped >300,000 sqm in 3D without running into memory issues.
