### ISSUE TITLE
drift problems even no movement?

### ISSUE THREAD

**Issue by tom8382** [googlecartographer/cartographer_ros#168]
when i let my robot in static status, i found that the estimate pose drift at very very little step, however, this give me cumulative total error 20cm after about 30min in bnoth x and y axis. maybe i set motion filter too sensitive or sometiong else wrong, how to debug my error?? thank you

and also, i found that the estimate pose will Influence by anything moves around it. some other slam algorithm, may consider abnormal characteristic points out of match process. how about carto, it seems that no obvious function in carto for this?thank you

**Comment by damonkohler** [comment]
We need to know more about your system to be able to answer this.

* Is this 2D or 3D?
* What's your configuration?
* What sort of environment?
* Can you provide a bag file?

Dynamic objects are handled by iterative "probability" updates to the map.

**Comment by tom8382** [comment]
thank you for reply. drift problem not happened certainly,i will record a bag if it happened as possible.

**Comment by damonkohler** [comment]
Ok, please open a new issue with as much information as possible if you need any help!
