### ISSUE TITLE
How to adjust the direction of the map for the horizontal and vertical ?

### ISSUE THREAD

**Issue by gogofight** [googlecartographer/cartographer_ros#170]
How to adjust the direction of the map for the horizontal and vertical from red to blue as follow ?

![demo](https://cloud.githubusercontent.com/assets/9596616/20380619/2da081ba-acde-11e6-8abb-a000c06833d5.png)

How to init map direction to any rotating degree or get it rightly ?

**Comment by damonkohler** [comment]
You can apply that rotation in some image editing software if you like. The orientation of the map is determined by the first trajectory pose (i.e. the origin of the map). If you'd like the resulting map to be aligned, you can try starting in a position that is aligned with the walls.

**Comment by zhamengkeji** [comment]
@damonkohler I would like to ask how the generated map is implemented with the coordinates of the world map.

**Comment by zhamengkeji** [comment]
@damonkohler How to achieve coordinates with world maps

**Comment by zhamengkeji** [comment]
@damonkohler How to achieve alignment with world map coordinates

**Comment by zhamengkeji** [comment]
@damonkohler 请问制图师发布的地图，怎么自动与世界地图坐标的对齐。

**Comment by zhamengkeji** [comment]
@damonkohler Is this related to the initial coordinates?
