### ISSUE TITLE
build fails optimization_problem.cc

### ISSUE THREAD

**Issue by herrhannes** [googlecartographer/cartographer_ros#176]
Build fails in optimization_problem.cc with "undefined reference to ceres::..."
commit 0c8d6afc33531761e8dd69760907d730a8440ed3 still worked, did not try the commits in between. Also, there seems to be an issue with configuration_files_test.
I am using ROS Kinetic on Ubuntu 16.04LTS.

**Comment by damonkohler** [comment]
Please provide the complete compilation output in a gist. Also, please provide the log from the configuration_files_test.

**Comment by herrhannes** [comment]
This is the output from `catkin_make_isolated --install --use-ninja`: https://gist.github.com/herrhannes/2dda1b811e9672aa7af6f211c60c107e 
The error with configuration_files_test is in line 1399 of the gist.

**Comment by tim-fan** [comment]
+1, I'm seeing the same build error. I'm also using ROS Kinetic and Ubuntu 16.04LTS. 

For me the build was passing as at commit https://github.com/googlecartographer/cartographer_ros/commit/e8b5dd6465dcea9bde47afd0496ca118bf063a10.

**Comment by herrhannes** [comment]
Commenting out the configuration_files_test makes it compilable. But I am not sure if that's really a solution and not just a treatment for the symptom.

**Comment by yoshito-okada** [comment]
> Commenting out the configuration_files_test makes it compilable.

This workaround worked for me too. I'm also using Ubuntu 16.04 + ROS kinetic.

BTW, my another computer having Ubuntu 14.04 + ROS jade could build the latest version as of today.

**Comment by herrhannes** [comment]
I think, this could be part of both, reason and solution:
https://github.com/ros/catkin/pull/782

**Comment by jeremymatthewwerner** [comment]
+1, I'm seeing the same build error. I'm also using ROS Kinetic and Ubuntu 16.04LTS.

**Comment by redheli** [comment]
+1 same build error , ROS Kinetic and Ubuntu 16.04LTS

spend whole day try to fix the issue...

**Comment by herrhannes** [comment]
I already opened an issue on github: https://github.com/googlecartographer/cartographer_ros/issues/176

 

Karlsruher Institut für Technologie (KIT)
Institut für Technik der Informationsverarbeitung (ITIV)

M. Sc. Hannes Stoll
Wissenschaftlicher Mitarbeiter

 
KIT – Die Forschungsuniversität in der Helmholtz-Gemeinschaft

 

Von: Max [mailto:notifications@github.com] 
Gesendet: Mittwoch, 30. November 2016 17:40
An: googlecartographer/cartographer_ros <cartographer_ros@noreply.github.com>
Cc: Stoll, Hannes (ITIV) <hannes.stoll@kit.edu>; Author <author@noreply.github.com>
Betreff: Re: [googlecartographer/cartographer_ros] build fails optimization_problem.cc (#176)

 

+1 same build error , ROS Kinetic and Ubuntu 16.04LTS

spend whole day try to fix the issue...

**Comment by redheli** [comment]
solution(not tested on Ubuntu 14.04):
add dependence **map_writer** to configuration_files_test

catkin_ws/src/cartographer_ros/cartographer_ros/cartographer_ros/CMakeLists.txt
```
google_test(configuration_files_test
  USES_CARTOGRAPHER
  SRCS
    configuration_files_test.cc
  DEPENDS
    map_writer
    node_options
)
```

**Comment by jeremymatthewwerner** [comment]
That fixed it for me on Ubuntu 14.04 - thank you so much!
Any reason _not_ to merge that change in?

- Jeremy

**Comment by jeremymatthewwerner** [comment]
Sorry I mean I'm on 16.04.

**Comment by SirVer** [comment]
Sorry, I was on vacation. Will have a look this week.

**Comment by ojura** [comment]
I can confirm the issue as well. Sounds to me that there are somewhere broken dependencies. I was able to get it to compile by taking a look at the linker invocation line (here's my build log: https://gist.github.com/ojura/fb9ab7c3a6b67dc99bfea3377ab40590) and adding additional linking calls to libceres.a after calls to libcartographer.a.
