### ISSUE TITLE
catkin_make_isolated --install --use-ninja giving error

### ISSUE THREAD

**Issue by kajariahridik** [googlecartographer/cartographer_ros#1769]
<== Failed to process package 'cartographer': 
  Command '['/home/hridik/catkin_ws/install_isolated/env.sh', 'ninja', '-j8', '-l8']' returned non-zero exit status 1.

How do I solve this error?

**Comment by Abhirup0209** [comment]
Did you actually solve the error?

**Comment by kajariahridik** [comment]
I did not solve it exactly, but I reinstalled ubuntu and started from scratch

**Comment by Abhirup0209** [comment]
And did it work?

I am getting this error:

FAILED: docs/CMakeFiles/build_doc 
cd /home/royabhi02/catkin_gc_ws/build_isolated/cartographer/install/docs && /usr/bin/sphinx-build -b html /home/royabhi02/catkin_gc_ws/src/cartographer/docs/source /home/royabhi02/catkin_gc_ws/build_isolated/cartographer/install/docs/html
Running Sphinx v1.8.5

Extension error:
Could not import extension sphinx.builders.latex (exception: cannot import name 'contextfunction' from 'jinja2' (/home/royabhi02/.local/lib/python3.8/site-packages/jinja2/__init__.py))
[327/333] Building CXX object CMakeFiles/cartographer.sensor.compressed_point_cloud_test.dir/cartographer/sensor/compressed_point_cloud_test.cc.o
ninja: build stopped: subcommand failed.
<== Failed to process package 'cartographer': 
  Command '['ninja', '-j8', '-l8']' returned non-zero exit status 1.

**Comment by yoggi56** [comment]
I've got the same error :(

**Comment by FPSychotic** [comment]
same error , why is closed?

**Comment by jhpark98** [comment]
I think it is the jinja version issue.

Based on this [comment](https://github.com/readthedocs/readthedocs.org/issues/9037), I updated jinja2 to 3.0.0.
` pip install jinja2==3.0.0 `
Same [issue](https://github.com/cartographer-project/cartographer_ros/issues/1795#issuecomment-1732041101) resolved with same idea.
