### ISSUE TITLE
How to rebuild after making changes on the launch and lua files?

### ISSUE THREAD

**Issue by Abhirup0209** [googlecartographer/cartographer_ros#1773]
I am making changes to the .lua file and the .launch files but then I cannot see the changes after i run:

roslaunch cartographer_ros demo_backpack_2d.launch bag_filename:='MY BAG FILE'

But i cannot see the changes which need to be reflected.

Can anyone help me please with how can i rebuild the workspace for my changes to be reflected properly?

**Comment by xiaodong2077** [comment]
you can simply change these files under devel dir without rebuilding.
