### ISSUE TITLE
[rospack] Error: package 'cartographer_rosbag_validate not found

### ISSUE THREAD

**Issue by ugrm** [googlecartographer/cartographer_ros#1830]
I'm getting this error when I try to validate my .bag file. My bagfile is outside of catkin_ws. How do I fix this problem? Do I need to move some folders around?
![image](https://github.com/cartographer-project/cartographer_ros/assets/145661518/61419036-d5e1-4f01-8725-0cecf25ddf97)
`jeahn@jeahn-VirtualBox:~$ rosrun cartographer_rosbag_validate -bag_filename 2024-06-20-11-57-44.bag
[rospack] Error: package 'cartographer_rosbag_validate' not found
jeahn@jeahn-VirtualBox:~$ rosrun cartographer_ros cartographer_rosbag_validate -bag_filename 2024-06-20-11-57-44.bag
[rospack] Error: package 'cartographer_ros' not found
jeahn@jeahn-VirtualBox:~$ `

**Comment by JaySlamer** [comment]
Go to the installed_isolated/bin directory to find it. Then run it like its a normal executable. No need to use rosrun.

**Comment by ugrm** [comment]
Thanks! It worked
