### ISSUE TITLE
MultiSense SL

### ISSUE THREAD

**Issue by athtest800** [googlecartographer/cartographer_ros#193]
Hello!
Does cartographer work with MultiSense SL Head?
[http://carnegierobotics.com/multisense-sl/](http://carnegierobotics.com/multisense-sl/)
Has anybody an example?
Thank you.

**Comment by damonkohler** [comment]
@skohlbr is doing something similar. As of #185 we support axially rotated scanners for 3D SLAM.

**Comment by skohlbr** [comment]
I actually even should have some Multisense SL bag files of Atlas walking around. I'm a bit busy in the next few days though, so will only be able to look for one later.

**Comment by damonkohler** [comment]
@skohlbr It would be great to have a configuration checked in for the Multisense. We're happy to host the bag :)

**Comment by athtest800** [comment]
@skohlbr Do we have some news on Multisense?
Thanks!
