### ISSUE TITLE
build - undefined reference to ceres

### ISSUE THREAD

**Issue by ESeNonFossiIo** [googlecartographer/cartographer_ros#205]
During the installation of *cartographer ros* using *catkin* I got this error: 
Here the complete [error](https://gist.github.com/ESeNonFossiIo/ff0f5afba8a92b57c131694a31f58aa3).
but the installation of ceres seems to be fine.
I am using Ubuntu 16.04.1 LTS + kinetic ROS.

**Comment by herrhannes** [comment]
https://github.com/googlecartographer/cartographer_ros/issues/176 ;)

**Comment by ESeNonFossiIo** [comment]
My fault... I was reading the google group and I forgot to check github's issues! :)
https://groups.google.com/forum/#!topic/google-cartographer/Kfx-Uizu_VY

**Comment by ESeNonFossiIo** [comment]
#176
