### ISSUE TITLE
Is it necessary to include IMU_link to run cartographer?

### ISSUE THREAD

**Issue by jvlevia** [googlecartographer/cartographer_ros#208]
I am trying to run my own bag file, but the bag file doesn't have IMU, it didn't work.

**Comment by damonkohler** [comment]
You'll need to change the configuration to match your own. You can disable the IMU, see revo_lds.lua for an example. You'll also have to provide a valid URDF to match your bag configuration.

**Comment by jvlevia** [comment]
Hi, is it the same to do with 3D map building ? I have tried to change the configuration, but it doesn't work.

**Comment by damonkohler** [comment]
I'm not sure I understand your issue. However, an IMU is required for 3D SLAM.
