### ISSUE TITLE
Import/Export question

### ISSUE THREAD

**Issue by droneflyers** [googlecartographer/cartographer_ros#243]
Hi! We have Cartographer up and running and have a Velodyne HDL 32E and a VLP16. We wanted to know how can we get both a nongeoferenced and geoferenced .ply/.las from an already configured .pcap? Any help would be greatly appreciated.

**Comment by damonkohler** [comment]
First, I suggest reaching out to http://answers.ros.org/ for help with getting the PCAP processed. Our node API is described here: https://google-cartographer-ros.readthedocs.io/en/latest/ros_api.html

Once you've generated a trajectory, you can use the asset writer (https://github.com/googlecartographer/cartographer_ros/blob/master/cartographer_ros/cartographer_ros/assets_writer_main.cc) to generate a PLY.

Cartographer does not currently integrate with GPS signals, so you will only be able to generate a non-georeferenced PLY.
