### ISSUE TITLE
Enquiry about IMU model

### ISSUE THREAD

**Issue by jvlevia** [googlecartographer/cartographer_ros#252]
May I ask what is the IMU model that has been used in the demo bag file, b3-2016-04-05-14-14-00.bag ?

**Comment by kentsommer** [comment]
@jvlevia 

It is a Microstrain IMU. If you want the specific model number perhaps someone else can get it for you.

**Comment by SirVer** [comment]
It is this one: 

http://www.microstrain.com/inertial/3dm-gx4-25
