### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by natalielucker** [googlecartographer/cartographer_ros#261]
Hi, I have an issue with Cartographer ROS build. Here is [build log](https://gist.github.com/natalielucker/d65ecf5f402c4ecc3bb8e45a782117da)
I'm running Ubuntu 16.04, ROS Kinetic.

**Comment by SirVer** [comment]
This is the problem:

>>> -- Found Lua: /usr/lib/x86_64-linux-gnu/liblua5.2.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "5.1.4") 

Your lua version is too old. You require lua 5.2 but have 5.1. The .so name looks wrong too, so it seems you over installed lua somehow.

**Comment by natalielucker** [comment]
Thank you, I'll update the Lua version on Monday, because now I don't have access to the workstation. Hope, it will work.
