### ISSUE TITLE
Problem getting simulated SLAM up and running 

### ISSUE THREAD

**Issue by SirVer** [googlecartographer/cartographer_ros#268]
Thread on the mailinglist:

 https://groups.google.com/d/msg/google-cartographer/ZQUwvfn7Nbw/cFYXhbYMBAAJ

**Comment by SirVer** [comment]
/cc @mohamadfarhat

Sorry for taking so long with this.

The [provided bag](https://www.dropbox.com/sh/ijzdht7cq9nd0i2/AADBtaSE9jmHgrvSPFEjoea4a?dl=0) contained a super noisy IMU with very large accelerations and the `/tf` topic contained various improperly timed tf messages.

My changes are in [this branch](https://github.com/googlecartographer/cartographer_ros/compare/master...SirVer:user/mohamadfarhat). I only filtered some of the bad `/tf` messages to reduce noise on the terminal. I then ran `roslaunch cartographer_ros 3d_google_cartographer.launch bag_filename:=$HOME/Downloads/sensoren_daten.bag`, waited for the completion of the rosbag, then ran  `rosservice call /finish_trajectory map`. This gave me the map below.

It is not perfect, but that is not surprising given the extreme IMU noise, but in general it works.

![map_xray_xy](https://cloud.githubusercontent.com/assets/140115/25710552/e330b04e-30ec-11e7-8da8-366f416659ed.png)

**Comment by mohamadfarhat** [comment]
@SirVer  Thanks you. You helped me a lot. I have another question. I read the Configuration and the ROS API.  Why IMU is required for using 3D Cartographer and optional for 2D? Why it is not Possible to use 3D Cartographer  without IMU? Thanks

**Comment by SirVer** [comment]
I added a FAQ entry for this question: https://google-cartographer-ros.readthedocs.io/en/latest/faq.html
