### ISSUE TITLE
compile point_cloud_viewer error

### ISSUE THREAD

**Issue by sunmk2006** [googlecartographer/cartographer_ros#271]
When I did the third step :“npm install", there was an error: npm WARN point_viewer@0.1.0 No repository field.but when I dit the fourth step:"npm run build",there were more errors:

    point_viewer@0.1.0 build /home/viki/soft/point_cloud_viewer-master/client
    tsc

main.ts(57,21): error TS2686: 'dat' refers to a UMD global, but the current file is a module. Consider adding an import instead.
node_modules/@types/whatwg-fetch/index.d.ts(11,13): error TS2451: Cannot redeclare block-scoped variable 'fetch'.
node_modules/@types/whatwg-fetch/index.d.ts(13,14): error TS2300: Duplicate identifier 'HeadersInit'.
node_modules/@types/whatwg-fetch/index.d.ts(14,15): error TS2300: Duplicate identifier 'Headers'.
node_modules/@types/whatwg-fetch/index.d.ts(31,14): error TS2300: Duplicate identifier 'BodyInit'.
node_modules/@types/whatwg-fetch/index.d.ts(43,14): error TS2300: Duplicate identifier 'RequestInfo'.
node_modules/@types/whatwg-fetch/index.d.ts(44,15): error TS2300: Duplicate identifier 'Request'.
node_modules/@types/whatwg-fetch/index.d.ts(64,11): error TS2300: Duplicate identifier 'Request'.
node_modules/@types/whatwg-fetch/index.d.ts(70,5): error TS2403: Subsequent variable declarations must have the same type. Variable 'referrerPolicy' must be of type 'string', but here has type 'ReferrerPolicy'.
node_modules/@types/whatwg-fetch/index.d.ts(71,5): error TS2403: Subsequent variable declarations must have the same type. Variable 'mode' must be of type 'string', but here has type 'RequestMode'.
node_modules/@types/whatwg-fetch/index.d.ts(72,5): error TS2403: Subsequent variable declarations must have the same type. Variable 'credentials' must be of type 'string', but here has type 'RequestCredentials'.
node_modules/@types/whatwg-fetch/index.d.ts(73,5): error TS2403: Subsequent variable declarations must have the same type. Variable 'cache' must be of type 'string', but here has type 'RequestCache'.
node_modules/@types/whatwg-fetch/index.d.ts(74,5): error TS2403: Subsequent variable declarations must have the same type. Variable 'redirect' must be of type 'string', but here has type 'RequestRedirect'.
node_modules/@types/whatwg-fetch/index.d.ts(76,5): error TS2403: Subsequent variable declarations must have the same type. Variable 'window' must be of type 'any', but here has type 'null'.
node_modules/@types/whatwg-fetch/index.d.ts(88,15): error TS2300: Duplicate identifier 'Response'.
node_modules/@types/whatwg-fetch/index.d.ts(107,11): error TS2300: Duplicate identifier 'Response'.
node_modules/@types/whatwg-streams/index.d.ts(32,15): error TS2300: Duplicate identifier 'ReadableStream'.
node_modules/typescript/lib/lib.es6.d.ts(12840,11): error TS2300: Duplicate identifier 'Headers'.
node_modules/typescript/lib/lib.es6.d.ts(12849,13): error TS2300: Duplicate identifier 'Headers'.
node_modules/typescript/lib/lib.es6.d.ts(15216,11): error TS2300: Duplicate identifier 'ReadableStream'.
node_modules/typescript/lib/lib.es6.d.ts(15222,13): error TS2300: Duplicate identifier 'ReadableStream'.
node_modules/typescript/lib/lib.es6.d.ts(15238,11): error TS2300: Duplicate identifier 'Request'.
node_modules/typescript/lib/lib.es6.d.ts(15255,13): error TS2300: Duplicate identifier 'Request'.
node_modules/typescript/lib/lib.es6.d.ts(15260,11): error TS2300: Duplicate identifier 'Response'.
node_modules/typescript/lib/lib.es6.d.ts(15271,13): error TS2300: Duplicate identifier 'Response'.
node_modules/typescript/lib/lib.es6.d.ts(20788,18): error TS2451: Cannot redeclare block-scoped variable 'fetch'.
node_modules/typescript/lib/lib.es6.d.ts(20793,6): error TS2300: Duplicate identifier 'BodyInit'.
node_modules/typescript/lib/lib.es6.d.ts(20814,6): error TS2300: Duplicate identifier 'HeadersInit'.
node_modules/typescript/lib/lib.es6.d.ts(20824,6): error TS2300: Duplicate identifier 'RequestInfo'.

npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/home/viki/.nvm/versions/node/v7.7.1/bin/node" "/home/viki/.nvm/versions/node/v7.7.1/bin/npm" "run" "build"
npm ERR! node v7.7.1
npm ERR! npm v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! point_viewer@0.1.0 build: tsc
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the point_viewer@0.1.0 build script 'tsc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the point_viewer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! tsc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs point_viewer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls point_viewer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /home/viki/soft/point_cloud_viewer-master/client/npm-debug.log

**Comment by SirVer** [comment]
Thank you. The problem seems that npm has a different understanding of semver than I am used to - some packages went out of backwards compatibility and did not work together anymore.

**Comment by sunmk2006** [comment]
build successfully, but：
viki@viki:/soft/point_cloud_viewer-master/target/release$ ls
build build_octree deps examples libpoint_viewer.rlib native viewer
viki@viki:/soft/point_cloud_viewer-master/target/release$ build_octree
build_octree: command not found
viki@viki:~/soft/point_cloud_viewer-master/target/release$

**Comment by sunmk2006** [comment]
./build_octree generates a lot of files,but
./viewer /home/viki/source/data/cartographer_data/mode 
Listening on port 5433.
IT seems to do nothing,  No changes in memory and CPU ，What happened？
