### ISSUE TITLE
Do you have some paper about 3D cartographer?

### ISSUE THREAD

**Issue by sunmk2006** [googlecartographer/cartographer_ros#280]

**Comment by damonkohler** [comment]
We have not yet written a paper about our 3D implementation.

**Comment by msy22** [comment]
Does that mean you are planning to write a paper on the 3D implementation? If so, what would be the ETA? If not, is there any available material on the 3D implementation? (other than source code).

Thanks in advance for any help or advice.

**Comment by SirVer** [comment]
We plan to write a paper, but have no ETA and no cycles to spent on it currently. 

There is no other documentation besides the source code, but the 3D implementation is a straightforward extension of the 2D approach, so the source code is probably the most educational.

**Comment by msy22** [comment]
Fantastic, thanks for the help!
