### ISSUE TITLE
motion state

### ISSUE THREAD

**Issue by sunmk2006** [googlecartographer/cartographer_ros#282]
when i use cartographer to do a 2D/3D slam, where is the boundary of the motion state of the device , Can it be used in vehicle systems?

**Comment by SirVer** [comment]
I do not understand the question. Are you asking what devices Cartographer can work on? We used Cartographer on cars, backpacks, bipedal, quatropedal and wheeled robots as well as quatrocopters.

**Comment by sunmk2006** [comment]
Can you tell me the speed of the vehicle？

**Comment by SirVer** [comment]
Highway driving and inner city driving.

**Comment by sunmk2006** [comment]
can cartographer  be  used for outdoor trajectory calculation？

**Comment by SirVer** [comment]
Yes.

**Comment by sunmk2006** [comment]
I am very worry about the motion distortion,do you have some answer for this question?

**Comment by SirVer** [comment]
Rightfully so. You have to take that into account. We did that for our example bags, see our [FAQ entry](https://google-cartographer-ros.readthedocs.io/en/latest/faq.html#the-laser-data-in-the-3d-bags-is-much-higher-than-the-maximum-reported-20-hz-rotation-speed-that-the-vlp-16-can-do-why). Cartographer SLAM does proper unwarping to fix for the motion distortion.
