### ISSUE TITLE
add IMU issue

### ISSUE THREAD

**Issue by cyy12345** [googlecartographer/cartographer_ros#298]
When I change the TRAJECTORY_BUILDER_2D.use_imu_data = false into true,I just find my cartographer can't run well. There is no map formed. I don't know what to do if I want to add the IMU data into cartographer node

**Comment by SirVer** [comment]
Have you investigated URDF tree issues? Have you made sure the frame name's are correct? Is the topic properly remapped? What is `roswtf` reporting?

**Comment by cyy12345** [comment]
Sorry, I can't give you the screenshot of my rviz, because I don't have my laser now. 
I think the main problem is that it shows "frame map does not exist".
And my launch file has   <remap from="scan" to="scan" />  I don't know is it correct

**Comment by cyy12345** [comment]
<launch>  
  <param name="/use_sim_time" value="true" />


  <node name="robot_state_publisher" pkg="robot_state_publisher"
    type="robot_state_publisher" />


  <node name="cartographer_node" pkg="cartographer_ros"  
      type="cartographer_node" args="  
          -configuration_directory $(find cartographer_ros)/configuration_files  
          -configuration_basename revo_lds.lua"  
      output="screen">  
    <remap from="scan" to="scan" />  
  </node>


  <node name="rviz" pkg="rviz" type="rviz" required="true"  
      args="-d $(find cartographer_ros)/configuration_files/demo_2d.rviz" /> 




 
</launch>

**Comment by SirVer** [comment]
Sounds like a ROS wiring issue to me, not per se Cartographer related. Did you have success asking on answers.ros.org with this?

**Comment by SirVer** [comment]
Closing as this is likely a ROS wiring issue, not a Cartographer issue. If you disagree, I will reopen.
