### ISSUE TITLE
separating rviz_plugin from cartographer_ros

### ISSUE THREAD

**Issue by jihoonl** [googlecartographer/cartographer_ros#308]
`cartographer_rviz` brings too big dependencies to install in a robot. Could we separate this package out as an independent repo called like `cartographer_ros_desktop`

**Comment by SirVer** [comment]
That is a valid request. This is theoretically simple too, but it is a rather big refactoring that we do not want to tackle right now. We gladly review PRs of course.

**Comment by jihoonl** [comment]
Can you create a new repo for `cartographer_rviz`? Then I will try to create PRs for refactoring

**Comment by damonkohler** [comment]
Done. There's now a cartographer_rviz repo.

**Comment by SirVer** [comment]
I think this just requires an FAQ entry now and can then be closed.

**Comment by SirVer** [comment]
In offline discussions we decided that the options ROS offers for excluding packages from building are sufficient to tackle this. #515 added a FAQ entry to explain how.
