### ISSUE TITLE
imu issue

### ISSUE THREAD

**Issue by sunmk2006** [googlecartographer/cartographer_ros#312]
Why 3D cartographer must have an IMU，but 2D cartographer can be not?

**Comment by damonkohler** [comment]
In 3D, the IMU integration is [part of the optimization](https://github.com/googlecartographer/cartographer/blob/master/cartographer/mapping_3d/sparse_pose_graph/optimization_problem.cc#L182). In 2D, it is used only to provide an initial estimate for scan matching and can be replaced with correlative scan matching.
