### ISSUE TITLE
Not creating odom or map

### ISSUE THREAD

**Issue by Cranapple** [googlecartographer/cartographer_ros#327]
Cartographer does not create the map or odom frame when run. It seems to be publishing submaps, but I can't visualize them in rviz.
It also repeatedly spits out the following info. After a while it significantly slows down and tends to crash, however it does publish matched points up until that point. I assume I'm just not setting something correctly but I'm having difficulty figuring out what exactly it is.

```
[ INFO] [1494024060.709986555]: I0505 15:41:00.000000 25283 constraint_builder.cc:300] 0 computations resulted in 0 additional constraints.
[ INFO] [1494024060.710090213]: I0505 15:41:00.000000 25283 constraint_builder.cc:302] Score histogram:
Count: 0
[ INFO] [1494024060.730095674]: I0505 15:41:00.000000 25283 sparse_pose_graph.cc:275] We caught up. Hooray!
```

roslaunch cartographer_ros kinect_baxter.launch
Rosbag: https://drive.google.com/file/d/0BwfwZjTRXXFdV1p0VnNtc3pNZzg/view?usp=sharing
Fork: https://github.com/Cranapple/cartographer_ros

**Comment by SirVer** [comment]
I cannot repro your issue. It works for me. Your bag is 42secs and do not contain movement, I created this map out of it: 
![map_xray_xy](https://cloud.githubusercontent.com/assets/140115/25799039/c3840cd8-33e3-11e7-8150-e76fb45154d6.png)

I only made [very minor changes](https://github.com/googlecartographer/cartographer_ros/commit/bdc96bf8f94e937e6c1dbc42401d24b9dc16b316).

- You told the system to attempt loop closure every 2 scans, which is very often. Usually you only attempt loop closure once or twice per submap. I changed that.
- Your sensor is very noisy and has a narrow field of view (compared to a laser). It does not constraint the SLAM problem in all dimensions well. I assume without additional data (IMU + wheels or so) you will have a hard time slamming with this device. It is also very, very noisy.
- I missed some ros packages to get your example running. I just commented them out and it seemed to have worked ok.
