### ISSUE TITLE
2D Cartographer Configuration problems

### ISSUE THREAD

**Issue by DumitritaCostinas** [googlecartographer/cartographer_ros#341]
I am trying to run the Cartographer in 2D using 2 Hokuyo UTM-30X-EW and one Microstrain 3DM-GX5-25. I have recorded my data in the file 2d.bag and when I try to run demo_backpack_2d I get the following warnings:

```
[ WARN] [1494942448.575425249, 1494937693.868806959]: W0516 15:47:28.000000 30705 ordered_multi_queue.cc:155] Queue waiting for data: (0, /horizontal_laser_2d)
[ WARN] [1494942448.575602871, 1494937693.889993492]: W0516 15:47:28.000000 30705 tf_bridge.cc:51] "imu" passed to lookupTransform argument target_frame does not exist. 
```

which cause my data to not be processed. When I run offline_backpack_2d I get the warning:

`[ WARN] [1494942746.995576646, 1494937683.671377604]: W0516 15:52:26.000000 30971 tf_bridge.cc:51] "laser" passed to lookupTransform argument source_frame does not exist. `

With the test data from the Deutsches Museum they are both working properly. Is it something obvious that I am doing wrong? 

Thank you for your time!

[GC.tar.gz](https://github.com/googlecartographer/cartographer_ros/files/1004662/GC.tar.gz)

**Comment by SirVer** [comment]
You use different `frame_id`s for your sensor data (both lasers use `laser`) and do not provide a URDF for the data to be transformed. This has nothing to do with Cartographer, it is a ROS configuration issue.

You can look at your data with rostopic echo <topic> to see this.
