### ISSUE TITLE
Do not preload all transforms into a tf_buffer in assets_writer_main.

### ISSUE THREAD

**Issue by SirVer** [googlecartographer/cartographer_ros#349]
I recently found that tf_buffer was so slow to be the bottleneck in the `offline_node` - especially for longer bags. We worked around this issues in #342 for the `offline_node`, but the same logic is also used in the `assets_writer_main` and should be changed there as well.

**Comment by at-wat** [comment]
FYI, I'm working on tf side to improve `tf_buffer` performance.
https://github.com/ros/geometry2/pull/267

In my case, that change makes `assets_writer` >20 times faster for 200k messages of /tf topic.
