### ISSUE TITLE
Trajectory visualization crashes

### ISSUE THREAD

**Issue by wohe** [googlecartographer/cartographer_ros#366]
RViz crashes after a while when trajectory visualization is enabled.

Reading through the RViz code it seems the line strip marker does not support lines with more than 16384 points. See
<https://github.com/ros-visualization/rviz/blob/kinetic-devel/src/rviz/ogre_helpers/billboard_line.cpp>. Maybe this is the issue?

Possible solution: Split longer trajectories into multiple line strip markers and see whether this fixes the crashes.

@ojura Do you want to try a fix? Feel free to unassign  if you would prefer me to look into it.

**Comment by wohe** [comment]
@ojura Seems I cannot assign you myself. Please let me know what you think.

**Comment by ojura** [comment]
I cannot assign myself either :-) I have reproduced it. I agree, it should be enough to just limit each `visualization_msgs::Marker` to 16384 (16383?) points, and to push as many additional markers as needed into the marker array.
