### ISSUE TITLE
Check failed: msg.range_min >= 0.f (-2.35183 vs. 0) 

### ISSUE THREAD

**Issue by OZzhuma** [googlecartographer/cartographer_ros#421]
i Build & Installation follow this :
![1](https://user-images.githubusercontent.com/17880969/28067384-af52e870-6673-11e7-8a72-6c1446aeaf2d.png)
 
but i I have encountered the following problem:
when i running
`roslaunch cartographer_ros demo_backpack_2d.launch bag_filename:=${HOME}/Downloads/cartographer_paper_deutsches_museum.bag`
it will occur
![2](https://user-images.githubusercontent.com/17880969/28067556-5ef31200-6674-11e7-870b-056167aaaf16.png)
but `roslaunch cartographer_ros demo_backpack_3d.launch bag_filename:=${HOME}/Downloads/cartographer_3d_deutsches_museum.bag` is ok

**Comment by wohe** [comment]
Could it be that the bag you are using is pretty old? I remember that we uploaded fixed bags when we added the check, i.e. you would simply have to download the new demo bag. The old bags by mistake contained negative min ranges as the check says.

**Comment by OZzhuma** [comment]
YES！The bag is pretty  old .I download the new bag and it works.
