### ISSUE TITLE
is there a bug in time_conversion.cc?

### ISSUE THREAD

**Issue by learnmoreonce** [googlecartographer/cartographer_ros#423]
In the line 44: 
(time.nsec + 50) / 100; 
why not ：(time.nsec + 50) / 1000; 
？

**Comment by wohe** [comment]
Why do you think there is a bug? The function is converting to universal time scale which is in 100 ns ticks and `time.nsec` are nanoseconds. Dividing by 1000 would result in microseconds, no?
