### ISSUE TITLE
Node::FinalizeTrajectory blocks callback servicing

### ISSUE THREAD

**Issue by ojura** [googlecartographer/cartographer_ros#476]
As I mentioned in #468, one final issue is that `MapBuilderBridge::FinalizeTrajectory()` (more precisely, when `SparsePoseGraph::RunFinalOptimization()` calls `SparsePoseGraph::WaitForAllComputations()`) can take a long time and make `Node::FinishTrajectory()` hold the `Node` mutex for too long. This blocks servicing submap requests and all other types of callbacks.  @wohe do you have a suggestion how to do more fine-grained locking?

**Comment by wohe** [comment]
The question is whether fine-grained locking is the solution here: Originally, `FinishTrajectory()` was not just finishing the trajectory but also wrote a map. For this map to be correctly optimized, we had to call `RunFinalOptimization()`. Now that writing the result is separate, I wonder whether we should rather move `RunFinalOptimization()` out of `FinishTrajectory()`. We could then not hold the mutex during the call to `FinishTrajectory()`. Note though, that no new data should arrive then as this is an assumption `WaitForAllComputations()` makes. Thoughts?

**Comment by ojura** [comment]
Great, that's more or less what I had in mind (when I mentioned "fine-grained locking").` I will prepare a PR and we can continue there.

**Comment by ojura** [comment]
By the way, does `sensor_bridges_.erase(trajectory_id)` have to be called after `RunFinalOptimization`?

**Comment by wohe** [comment]
I don't think so. You might want to check, but I think sensor bridges are only accessed until subscribers are removed which happens before the call to `FinishTrajectory()`.
