### ISSUE TITLE
Cannot Build cartographer_ros

### ISSUE THREAD

**Issue by HazenDean** [googlecartographer/cartographer_ros#484]
I tried building cartographer on a ROS system, but I am running into some issues:

error: 'const TrajectoryOptions' has no member named 'num_laser_scans'
   options->num_laser_scans = msg.num_laser_scans;

error: 'const TrajectoryOptions' has no member named 'num_multi_echo_laser_scans'
   options->num_laser_scans = msg.num_multi_echo_laser_scans;

I built according to the instructions at https://google-cartographer.readthedocs.io/en/latest/ and https://google-cartographer-ros-for-turtlebots.readthedocs.io/en/latest/

**Comment by damonkohler** [comment]
It sounds like not all of your repos are up-to-date with head. Make sure you pull in both cartographer and cartographer_ros to get the latest version.
