### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by jmloveyj** [googlecartographer/cartographer_ros#487]
The build error log is listed below: (I guess cartographer make some changes that impact the build)
/mnt/slam/src/cartographer_ros/cartographer_ros/cartographer_ros/assets_writer_main.cc: In function ‘void cartographer_ros::{anonymous}::Run(const string&, const std::vector<std::basic_string<char> >&, const string&, const string&, const string&)’:
/mnt/slam/src/cartographer_ros/cartographer_ros/cartographer_ros/assets_writer_main.cc:200:11: error: ‘FromTrajectory’ is not a member of ‘cartographer::transform::TransformInterpolationBuffer’
           carto::transform::TransformInterpolationBuffer::FromTrajectory(
           ^
[31/36] Building CXX object cartographer_ros/C...rapher_offline_node.dir/offline_node_main.cc.o
ninja: build stopped: subcommand failed.
<== Failed to process package 'cartographer_ros': 
  Command '['/mnt/slam/devel_isolated/cartographer/env.sh', 'ninja', '-j4', '-l4']' returned non-zero exit status 1

Reproduce this error by running:
==> cd /mnt/slam/build_isolated/cartographer_ros && /mnt/slam/devel_isolated/cartographer/env.sh ninja -j4 -l4

Command failed, exiting.

**Comment by wohe** [comment]
This sounds like you are using a recent version of the `cartographer` repo without having synced past #486. Updating your version of `cartographer_ros` should fix this.
