### ISSUE TITLE
Could you please give me some instructions about which parts of the Cartographer should I modify to adapt it to the xv-11 lidar?

### ISSUE THREAD

**Issue by csyyzhang** [googlecartographer/cartographer_ros#496]
Could you please give me some instructions about which parts of the Cartographer should I modify to adapt it to the xv-11 lidar?

Basically, I want to test the performance of Cartographer ros when it is connected to xv-11 lidar.

**Comment by BrannonKing** [comment]
You should close this issue (as it's not a defect) and ask the same question in the news group.

You have nothing but laser data? If so, use the realtime scan matcher. You will need to set the min/max_range parameters in the lua file. I don't think that you need to configure most other values.
