### ISSUE TITLE
the poor effect of repeated closed loop

### ISSUE THREAD

**Issue by sunmk2006** [googlecartographer/cartographer_ros#531]
hello, I am tuning 3d cartographer for my vel-16 data,but the effect of repeated closed loop is poor，I can't solve it,can you help me?
the configuration files , launch file, urdf file and result png files is [here ](https://github.com/sunmk2006/cartographer_ros/blob/master/slam_3d_loop.zip),and the bag file is [here](http://pan.baidu.com/s/1pL7eZDh).

![screenshot from 2017-10-10 16_24_00](https://user-images.githubusercontent.com/17526115/31378129-db6c2dd0-addc-11e7-90c9-6fdbfb7ccfa8.png)

**Comment by Mofef** [comment]
On first glance SPARSE_POSE_GRAPH.constraint_builder.min_score = 0.7 seems very high to me try something like ~0.55

**Comment by SirVer** [comment]
@sunmk2006 We mentioned some problems with your data in #509 already. Could you first comment on the issues before we further investigate? Most surprising to us is that you have the exact same number of IMU messages than VLP16 packets which seem nonphysical.

**Comment by sunmk2006** [comment]
Sorry, I didn't respond to your comments in time. 

> the exact same number of IMU messages than VLP16 packets 

This phenomenon stems from a synchronous approach，locate the IMU data based on the received laser timestamp，Because my IMU device and laser device do not work at the same time, the data of the two are not collected simultaneously.The recently uploaded bag data file does not pay attention to the synchronization of the two, and directly to the cartographer processing.Is there any problem with this method?

**Comment by SirVer** [comment]
> Is there any problem with this method?

Yes, it is. The synchronization is actually sub-optimal - it means that you integrate your IMU data for longer than necessary, leading to larger errors. Why are you doing this?

We will investigate your other bag in #509, I reopened the issue. Maybe a solution for this one comes out of that as well.

**Comment by sunmk2006** [comment]
@Mofef  I have changed the parameter , but the problem still exists

**Comment by sunmk2006** [comment]
> Why are you doing this?
Still based on data synchronization considerations，I think in advance to do data synchronization, the effect will be better.

**Comment by SirVer** [comment]
> Still based on data synchronization considerations，I think in advance to do data synchronization, the effect will be better.

I do not understand that reasoning. Why should synchronized data collection better? More data will always be better than subsampling.

> I also did UDP processing, but the effect is not very good.

Not sure what you mean with this.

**Comment by sunmk2006** [comment]
> More data will always be better than subsampling.
If the timestamp of the first IMU data in the bag file is 1000.000001 (second), the timestamp of the first laser data is 1020.000001 (second). Can the cartographer automatically synchronize the two data? 

> I also did UDP processing, but the effect is not very good.
Later, I'll upload the bag file in UDP form to the Internet

**Comment by SirVer** [comment]
> If the timestamp of the first IMU data in the bag file is 1000.000001 (second), the timestamp of the first laser data is 1020.000001 (second). Can the cartographer automatically synchronize the two data?

The offline node does this automatically. The online node could too, but ROS cannot deal with this (as it tries to transform the data and TF buffers are not that long). It seems unphysical that your sensor offset is that big and constant - how did that happen?

Closing this following the analysis in https://github.com/googlecartographer/cartographer_ros/issues/509#issuecomment-336484002.

**Comment by ojura** [comment]
If there's a fixed offset between the two sensors, just account for it in their timestamps. No need to change the sample rate.

**Comment by SirVer** [comment]
@ojura It isn't a fixed offset, see our analysis in the linked comment.

**Comment by sunmk2006** [comment]
![03](https://user-images.githubusercontent.com/17526115/31761260-e6aaadb6-b4e9-11e7-90b8-dd7651948fc4.jpg)

**Comment by sunmk2006** [comment]
the new configuration files and png files is [here](https://github.com/sunmk2006/cartographer_ros/blob/master/configuration_files_frame.zip)
![screenshot from 2017-10-24 15 34 06](https://user-images.githubusercontent.com/17526115/31983849-b4a928e0-b991-11e7-8fc0-0ecac8a05a6c.png)

**Comment by SirVer** [comment]
@sunmk2006 Could you host your bags somewhere else? Downloading your bag from baidu takes > 10 hours here in Germany and the connection terminates regularly. Google Drive is better replicated and would be preferable.

**Comment by sunmk2006** [comment]
OK， but I can't use Google drive, I will reduce the bag file or try another cloud disk.

**Comment by sunmk2006** [comment]
@SirVer hello,a new link is [here](http://www.babel.cc/share.do?s=1114663790085936),You can test the download speed over there, and if the speed is still slow, I'll look for other cloud disks

**Comment by SirVer** [comment]
Does the new link requires an account? I have trouble with the chinese.

**Comment by sunmk2006** [comment]
No account required，please open the link, Put the mouse on the line of test_03.bag.zip，[Click the second buttons that appear](https://github.com/sunmk2006/cartographer_ros/blob/master/20171025191607.jpg)

**Comment by sunmk2006** [comment]
https://github.com/sunmk2006/cartographer_ros/blob/master/20171025191607.jpg

**Comment by SirVer** [comment]
that link opens a different looking page for me: 
![2017-10-25-144036_2560x1572_scrot](https://user-images.githubusercontent.com/140115/31999159-a8e7402c-b992-11e7-8b3d-344f42c4929a.png)

**Comment by sunmk2006** [comment]
ok，i have an account 18037109891 and the passwd is 632851

**Comment by sunmk2006** [comment]
I added two more links. See if you can use them
[link1](https://v2.fangcloud.com/share/a51cdc038358d5f61361731996) 
[link2](http://pan.baidu.com/s/1bp8Qnin)

**Comment by gaschler** [comment]
Timing of sensor data now seems fine, we had a look into the graphs. Some gaps in laser data are still present but not in the first seconds, so they don't explain why tracking fails.

I had a look at your bag file with
`rqt_bag ~/Downloads/test_03.bag`
and observed that IMU acceleration in z-axis is positive in this bag.
For this, the urdf setting 
`<child link="imu" />  <origin xyz="0 0 0" rpy="3.1416 0 0" />`
cannot be correct. Gravity should be pointing down.

Perhaps you can share photos of how the sensors are attached to your robot?

**Comment by sunmk2006** [comment]
sorry,  I should update the urdf file,the imu to base_link rpy should "0 0 3.1415926"

>   <joint name="imu_link_joint" type="fixed">
    <parent link="base_link" />
    <child link="imu" />
    <origin xyz="0 0 0" rpy="0 0 3.1415926" />
  </joint>

**Comment by gaschler** [comment]
I also tried this, quality was low again. Are you entirely sure the timing of the imu matches the laser scans?

Investigating this further will be hard without 
- photos of the setup to ensure the urdf transforms are correct
- a fork that we can simply run and test without any copy-paste.

**Comment by sunmk2006** [comment]
Okay, I'll upload a picture of the device later，below is a URDF model, the relative position is correspond with actual position of equipment , the problem is that in the ROS coordinates  x-->forward,  y-->left, z-->up, but x-->left,but my own coordinates x-->right,y-->forward, z-->up, because the IMU around the Z axis rotation to 180 degrees (yaw = 3.1415926 rad) ,the coordinates of IMU is x-->left, y-->backward, z-->up,How can I tell the cartographer system about these changes?

![screenshot from 2017-10-27 10 13 36](https://user-images.githubusercontent.com/17526115/32085081-a90ac8da-baff-11e7-86e9-1a009f13e16f.png)

**Comment by SirVer** [comment]
> How can I tell the cartographer system so many changes about the coordinates?

Through the URDF.

> In addition, is it possible that those configuration parameters (lua files)causes the problem?

Not the Lua files. But if your URDF is wrong your IMU and Laser are constantly disagreeing, so that would be definitively lead to the fragility we observe.

**Comment by gaschler** [comment]
As I said, I observed that IMU acceleration in z-axis is positive in your bag.
In my eyes, this does not match the upwards IMU z-axis in the first picture.
Before any fine tuning, you need to correct the URDF first.

**Comment by sunmk2006** [comment]
my imu device model is xsens MTI-G-700 ,I use the official equipment software to do an experiment, when the device is placed upright, Z acceleration is positive ,when placed upside down, Z acceleration is negative

**Comment by gaschler** [comment]
If your IMU reads (negative) -10m/s^2, your URDF settings should be that the z-axis (blue) of IMU points upward.
If it reads positive, z-axis should be configured downward.

For the other axes, we would need more information.
