### ISSUE TITLE
problem when building map 

### ISSUE THREAD

**Issue by yinnxinn** [googlecartographer/cartographer_ros#535]
when building map using cartographer , there would be a strange stride in the map , the trajectory would forward while the robot didn't move like that . as the follow pictures show:
 
![Uploading Screenshot from 2017-10-13 15_38_42.png…]()
![Uploading Screenshot from 2017-10-13 15_46_37.png…]()

    And the ScanLaser became very vague like this 

![Uploading Screenshot from 2017-10-13 15_46_17.png…]()
![Uploading Screenshot from 2017-10-13 15_46_24.png…]()

    Have anyone met this problem or provide some issues why this happened ???

    the laser device I used is ## ## SICK.

**Comment by SirVer** [comment]
This bug report does not contain configuration files, bag, commandline or screenshots. Closing as non actionable. 

If you want help with this, please make a new bug report and follow the bug template. We will be unable to help otherwise.
