### ISSUE TITLE
problem when building map

### ISSUE THREAD

**Issue by yinnxinn** [googlecartographer/cartographer_ros#539]
when building map using cartographer , there would be a strange stride in the map , the trajectory would forward while the robot didn't move like that . as the follow pictures show:
![screenshot from 2017-10-13 15 46 37](https://user-images.githubusercontent.com/23116748/31545227-18de95c4-b051-11e7-804c-ddaf628a923f.png)
![screenshot from 2017-10-13 19 56 17](https://user-images.githubusercontent.com/23116748/31545160-d01b82a2-b050-11e7-8226-5bcf45981cbc.png)

   on the stride stage , the laser data become very vague , like this 
![screenshot from 2017-10-13 15 38 42](https://user-images.githubusercontent.com/23116748/31545173-e44a123e-b050-11e7-937d-b5aa9175f981.png)

#        my configure file :

options = {
  map_builder = MAP_BUILDER,
  trajectory_builder = TRAJECTORY_BUILDER,
  map_frame = "map",
  tracking_frame = "laser",
  published_frame = "laser",
  odom_frame = "odom",
  provide_odom_frame = true,
  use_odometry = false,
  num_laser_scans = 1,
  num_multi_echo_laser_scans = 0,
  num_subdivisions_per_laser_scan = 1,
  num_point_clouds = 0,
  lookup_transform_timeout_sec = 0.2,
  submap_publish_period_sec = 0.3,
  pose_publish_period_sec = 5e-3,
  trajectory_publish_period_sec = 30e-3,
}

MAP_BUILDER.use_trajectory_builder_2d = true

TRAJECTORY_BUILDER_2D.submaps.num_range_data = 35
TRAJECTORY_BUILDER_2D.min_range = 0.05
TRAJECTORY_BUILDER_2D.max_range = 10.
TRAJECTORY_BUILDER_2D.missing_data_ray_length = 1.
TRAJECTORY_BUILDER_2D.use_imu_data = false
TRAJECTORY_BUILDER_2D.use_online_correlative_scan_matching = true
TRAJECTORY_BUILDER_2D.real_time_correlative_scan_matcher.linear_search_window = 0.1
TRAJECTORY_BUILDER_2D.real_time_correlative_scan_matcher.translation_delta_cost_weight = 10.
TRAJECTORY_BUILDER_2D.real_time_correlative_scan_matcher.rotation_delta_cost_weight = 1e-1

SPARSE_POSE_GRAPH.optimization_problem.huber_scale = 1e2
SPARSE_POSE_GRAPH.optimize_every_n_scans = 10
SPARSE_POSE_GRAPH.constraint_builder.min_score = 0.65

    Have anyone met this problem ? ?

**Comment by SirVer** [comment]
No bag file, no launch file, no urdf - still not actionable :(. Closing again.
