### ISSUE TITLE
2D pure localization fails on same map, finds old constraints.

### ISSUE THREAD

**Issue by gladxu** [googlecartographer/cartographer_ros#557]
1.roslaunch cartographer_ros demo_backpack_2d.launch bag_filename:="full path to cartographer_paper_deutsches_museum.bag"

2.rosservice call /finish_trajectory "trajectory_id: 0"
   rosservice call /write_state "filename: 'demo_2d.state'" 

3.roslaunch cartographer_ros demo_backpack_2d_localization.launch bag_filename:="full path to cartographer_paper_deutsches_museum.bag" map_filename:="path to demo_2d.state"

![screenshot from 2017-10-26 16 01 09](https://user-images.githubusercontent.com/18653443/32043175-8f2491aa-ba6c-11e7-8d15-2ebac4b81631.png)

The pure localization trajectory(in green) is away from the map trajectory(in blue) as times go by;
it seems there are new submaps added and new submaps are not consist with the map file;

It is supposed that the pose of pure localization is refer to map file;and the update of map should keep consistent.
Is there something wrong?

cartographer_ros (git head)
commit 137c75633f94dd64edbd9ae9ae05d4ad5dd6b459
Author: Holger Rapp <HolgerRapp@gmx.net>
Date:   Mon Oct 23 10:40:43 2017 +0200

    Adds a PointsProcessor that can write ROS maps. (#548)
    
    Fixes #475.

cartographer(git head)
commit 638aee7c2a6c7a70d2a7da39f4551b6cc6d8b318
Author: Holger Rapp <HolgerRapp@gmx.net>
Date:   Mon Oct 23 10:56:55 2017 +0200

    Fix slow point deletion in RemovePoints. (#608)
    
    This speeds up the asset writer significantly:
    
    For the 3D sample bag:

**Comment by gaschler** [comment]
Thanks for reporting and providing a helpful screenshot. This is a cartographer bug, so I close this an follow up in https://github.com/googlecartographer/cartographer/issues/647
