### ISSUE TITLE
Non-sorted data added to queue: '(0, points2)'

### ISSUE THREAD

**Issue by Calvin4016** [googlecartographer/cartographer_ros#571]
Dear Cartographer developers,

I have a couple issues that I could not fix on my own and I'm seeking help. I am using a VLP-16 and an IMU. When I launch a lightly modified version of lua, urdf, and launch files found here: https://gist.github.com/Vincent1923/9b4dd8bbfd9301dd408e89f6e21cead7 , I received the following error message: (first it's showing "IMU not yet initialized" but I made sure my IMU is publishing valid and reasonable numbers, then shown with a FATAL error, I've highlighted them with Bold font)

<My modified version can be found here: https://github.com/Calvin4016/cartographer_ros >

SUMMARY

PARAMETERS
 * /pointcloud_to_laserscan/angle_increment: 0.0087
 * /pointcloud_to_laserscan/angle_max: 3.14
 * /pointcloud_to_laserscan/angle_min: -3.14
 * /pointcloud_to_laserscan/concurrency_level: 1
 * /pointcloud_to_laserscan/max_height: 1.0
 * /pointcloud_to_laserscan/min_height: 0.0
 * /pointcloud_to_laserscan/range_max: 130.0
 * /pointcloud_to_laserscan/range_min: 0.4
 * /pointcloud_to_laserscan/scan_time: 0.3333
 * /pointcloud_to_laserscan/target_frame: velodyne
 * /pointcloud_to_laserscan/transform_tolerance: 0.01
 * /pointcloud_to_laserscan/use_inf: True
 * /robot_description: <...>
 * /rosdistro: kinetic
 * /rosversion: 1.12.7
 * /use_sim_time: True
 * /velodyne_nodelet_manager_cloud/calibration: /home/ANT.AMAZON....
 * /velodyne_nodelet_manager_cloud/max_range: 130.0
 * /velodyne_nodelet_manager_cloud/min_range: 0.4
 * /velodyne_nodelet_manager_driver/device_ip: 
 * /velodyne_nodelet_manager_driver/frame_id: velodyne
 * /velodyne_nodelet_manager_driver/model: VLP16
 * /velodyne_nodelet_manager_driver/pcap: 
 * /velodyne_nodelet_manager_driver/port: 2368
 * /velodyne_nodelet_manager_driver/read_fast: False
 * /velodyne_nodelet_manager_driver/read_once: False
 * /velodyne_nodelet_manager_driver/repeat_delay: 0.0
 * /velodyne_nodelet_manager_driver/rpm: 600.0

NODES
  /
    cartographer_node (cartographer_ros/cartographer_node)
    cartographer_occupancy_grid_node (cartographer_ros/cartographer_occupancy_grid_node)
    playbag (rosbag/play)
    pointcloud_to_laserscan (pointcloud_to_laserscan/pointcloud_to_laserscan_node)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rviz (rviz/rviz)
    static_transform_publisher3 (tf/static_transform_publisher)
    velodyne_nodelet_manager (nodelet/nodelet)
    velodyne_nodelet_manager_cloud (nodelet/nodelet)
    velodyne_nodelet_manager_driver (nodelet/nodelet)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[velodyne_nodelet_manager-1]: started with pid [20416]
process[velodyne_nodelet_manager_driver-2]: started with pid [20417]
process[velodyne_nodelet_manager_cloud-3]: started with pid [20418]
process[pointcloud_to_laserscan-4]: started with pid [20419]
process[robot_state_publisher-5]: started with pid [20425]
process[static_transform_publisher3-6]: started with pid [20437]
process[cartographer_node-7]: started with pid [20447]
process[cartographer_occupancy_grid_node-8]: started with pid [20452]
process[rviz-9]: started with pid [20464]
process[playbag-10]: started with pid [20474]
[ INFO] [1509674459.047857414]: I1102 19:00:59.000000 20447 configuration_file_resolver.cc:40] Found '/home/ANT.AMAZON.COM/hwguo/Cartographer_ws/install_isolated/share/cartographer_ros/configuration_files/vlp16-imu.lua' for 'vlp16-imu.lua'.
[ INFO] [1509674459.048119201]: I1102 19:00:59.000000 20447 configuration_file_resolver.cc:40] Found '/home/ANT.AMAZON.COM/hwguo/Cartographer_ws/install_isolated/share/cartographer/configuration_files/map_builder.lua' for 'map_builder.lua'.
[ INFO] [1509674459.048157569]: I1102 19:00:59.000000 20447 configuration_file_resolver.cc:40] Found '/home/ANT.AMAZON.COM/hwguo/Cartographer_ws/install_isolated/share/cartographer/configuration_files/map_builder.lua' for 'map_builder.lua'.
[ INFO] [1509674459.048211947]: I1102 19:00:59.000000 20447 configuration_file_resolver.cc:40] Found '/home/ANT.AMAZON.COM/hwguo/Cartographer_ws/install_isolated/share/cartographer/configuration_files/sparse_pose_graph.lua' for 'sparse_pose_graph.lua'.
[ INFO] [1509674459.048243295]: I1102 19:00:59.000000 20447 configuration_file_resolver.cc:40] Found '/home/ANT.AMAZON.COM/hwguo/Cartographer_ws/install_isolated/share/cartographer/configuration_files/sparse_pose_graph.lua' for 'sparse_pose_graph.lua'.
[ INFO] [1509674459.048364437]: I1102 19:00:59.000000 20447 configuration_file_resolver.cc:40] Found '/home/ANT.AMAZON.COM/hwguo/Cartographer_ws/install_isolated/share/cartographer/configuration_files/trajectory_builder.lua' for 'trajectory_builder.lua'.
[ INFO] [1509674459.048395148]: I1102 19:00:59.000000 20447 configuration_file_resolver.cc:40] Found '/home/ANT.AMAZON.COM/hwguo/Cartographer_ws/install_isolated/share/cartographer/configuration_files/trajectory_builder.lua' for 'trajectory_builder.lua'.
[ INFO] [1509674459.048443667]: I1102 19:00:59.000000 20447 configuration_file_resolver.cc:40] Found '/home/ANT.AMAZON.COM/hwguo/Cartographer_ws/install_isolated/share/cartographer/configuration_files/trajectory_builder_2d.lua' for 'trajectory_builder_2d.lua'.
[ INFO] [1509674459.048468806]: I1102 19:00:59.000000 20447 configuration_file_resolver.cc:40] Found '/home/ANT.AMAZON.COM/hwguo/Cartographer_ws/install_isolated/share/cartographer/configuration_files/trajectory_builder_2d.lua' for 'trajectory_builder_2d.lua'.
[ INFO] [1509674459.048545344]: I1102 19:00:59.000000 20447 configuration_file_resolver.cc:40] Found '/home/ANT.AMAZON.COM/hwguo/Cartographer_ws/install_isolated/share/cartographer/configuration_files/trajectory_builder_3d.lua' for 'trajectory_builder_3d.lua'.
[ INFO] [1509674459.048577789]: I1102 19:00:59.000000 20447 configuration_file_resolver.cc:40] Found '/home/ANT.AMAZON.COM/hwguo/Cartographer_ws/install_isolated/share/cartographer/configuration_files/trajectory_builder_3d.lua' for 'trajectory_builder_3d.lua'.
[ INFO] [1509674459.057888695]: I1102 19:00:59.000000 20447 submaps.cc:294] Added submap 1
[ INFO] [1509674459.057948980]: I1102 19:00:59.000000 20447 map_builder_bridge.cc:82] Added trajectory with ID '0'.
[ INFO] [1509674459.667366551, 1509668414.989304821]: I1102 19:00:59.000000 20447 ordered_multi_queue.cc:172] All sensor data for trajectory 0 is available starting at '636452652149545570'.
**_[ INFO] [1509674459.671253351, 1509668414.989304821]: I1102 19:00:59.000000 20447 local_trajectory_builder.cc:67] IMU not yet initialized._**
[ INFO] [1509674472.451826065, 1509668440.546010709]: I1102 19:01:12.000000 20447 motion_filter.cc:42] Motion filter reduced the number of scans to 28.2%.
[ INFO] [1509674474.058984605, 1509668443.765786482]: I1102 19:01:14.000000 20447 collated_trajectory_builder.cc:74] imu rate: 99.86 Hz 1.00e-02 s +/- 8.62e-04 s (pulsed at 199.96% real time)
[ INFO] [1509674474.059035944, 1509668443.765786482]: I1102 19:01:14.000000 20447 collated_trajectory_builder.cc:74] points2 rate: 19.62 Hz 5.10e-02 s +/- 5.05e-02 s (pulsed at 200.43% real time)
F1102 19:01:16.333724 20447 ordered_multi_queue.cc:112] Check failed: last_dispatched_time_ <= next_data->GetTime() (636452652482733020 vs. 636452652481796770) Non-sorted data added to queue: '(0, points2)'
**[FATAL] [1509674476.334053794, 1509668448.325840037]: F1102 19:01:16.000000 20447 ordered_multi_queue.cc:112] Check failed: last_dispatched_time_ <= next_data->GetTime() (636452652482733020 vs. 636452652481796770) Non-sorted data added to queue: '(0, points2)'**
*** Check failure stack trace: ***
    @     0x7fbc3517d5cd  google::LogMessage::Fail()
    @     0x7fbc3517f433  google::LogMessage::SendToLog()
    @     0x7fbc3517d15b  google::LogMessage::Flush()
    @     0x7fbc3517fe1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x5c0c6c  cartographer::sensor::OrderedMultiQueue::Dispatch()
    @           0x5c1b44  cartographer::sensor::OrderedMultiQueue::Add()
    @           0x5be9b5  cartographer::sensor::Collator::AddSensorData()
    @           0x5e0ed8  cartographer::mapping::CollatedTrajectoryBuilder::AddSensorData()
    @           0x534577  cartographer_ros::SensorBridge::HandleRangefinder()
    @           0x5358f2  cartographer_ros::SensorBridge::HandlePointCloud2Message()
    @           0x508a69  cartographer_ros::Node::HandlePointCloud2Message()
    @           0x517b9e  boost::detail::function::void_function_obj_invoker1<>::invoke()
    @           0x5217c9  ros::SubscriptionCallbackHelperT<>::call()
    @     0x7fbc32cfc5dd  ros::SubscriptionQueue::call()
    @     0x7fbc32ca6cf0  ros::CallbackQueue::callOneCB()
    @     0x7fbc32ca80f3  ros::CallbackQueue::callAvailable()
    @     0x7fbc32d006a1  ros::SingleThreadedSpinner::spin()
    @     0x7fbc32ce573b  ros::spin()
    @           0x5012b1  cartographer_ros::(anonymous namespace)::Run()
    @           0x4ff774  main
    @     0x7fbc316fe830  __libc_start_main
    @           0x500e69  _start
    @              (nil)  (unknown)
**[cartographer_node-7] process has died [pid 20447, exit code -6, cmd /home/ANT.AMAZON.COM/hwguo/Cartographer_ws/install_isolated/lib/cartographer_ros/cartographer_node -configuration_directory /home/ANT.AMAZON.COM/hwguo/Cartographer_ws/install_isolated/share/cartographer_ros/configuration_files -configuration_basename vlp16-imu.lua points2:=velodyne_points imu:=imu/chassis __name:=cartographer_node __log:=/home/ANT.AMAZON.COM/hwguo/.ros/log/1b79f64a-c026-11e7-b40d-1c4d709c96db/cartographer_node-7.log].
log file: /home/ANT.AMAZON.COM/hwguo/.ros/log/1b79f64a-c026-11e7-b40d-1c4d709c96db/cartographer_node-7*.log*

===================================================================

By running the analysis, I got:

E1102 19:10:40.220289 24648 rosbag_validate_main.cc:137] frame_id "velodyne" is send on multiple topics. It was seen at least on /scan and /velodyne_points
E1102 19:10:40.220932 24648 rosbag_validate_main.cc:137] frame_id "velodyne" is send on multiple topics. It was seen at least on /scan and /velodyne_points
I1102 19:10:40.236191 24648 rosbag_validate_main.cc:154] Time delta histogram for consecutive messages on topic "/imu/chassis" (frame_id: "imu_chassis"):
Count: 12828  Min: 0.001245  Max: 0.025945  Mean: 0.010015
[0.001245, 0.003715)	                    	Count: 12 (0.093545%)	Total: 12 (0.093545%)
[0.003715, 0.006185)	                    	Count: 109 (0.849704%)	Total: 121 (0.943249%)
[0.006185, 0.008655)	                    	Count: 186 (1.449953%)	Total: 307 (2.393202%)
[0.008655, 0.011125)	 ###################	Count: 12179 (94.940758%)	Total: 12486 (97.333954%)
[0.011125, 0.013595)	                    	Count: 201 (1.566885%)	Total: 12687 (98.900841%)
[0.013595, 0.016065)	                    	Count: 110 (0.857499%)	Total: 12797 (99.758339%)
[0.016065, 0.018535)	                    	Count: 14 (0.109136%)	Total: 12811 (99.867477%)
[0.018535, 0.021005)	                    	Count: 7 (0.054568%)	Total: 12818 (99.922043%)
[0.021005, 0.023475)	                    	Count: 3 (0.023386%)	Total: 12821 (99.945435%)
[0.023475, 0.025945]	                    	Count: 7 (0.054568%)	Total: 12828 (100.000000%)
I1102 19:10:40.236317 24648 rosbag_validate_main.cc:154] Time delta histogram for consecutive messages on topic "/scan_matched_points2" (frame_id: "map"):
Count: 1278  Min: 0.090836  Max: 0.110808  Mean: 0.100860
[0.090836, 0.092833)	                    	Count: 2 (0.156495%)	Total: 2 (0.156495%)
[0.092833, 0.094830)	                    	Count: 2 (0.156495%)	Total: 4 (0.312989%)
[0.094830, 0.096828)	                    	Count: 0 (0.000000%)	Total: 4 (0.312989%)
[0.096828, 0.098825)	                    	Count: 8 (0.625978%)	Total: 12 (0.938967%)
[0.098825, 0.100822)	                ####	Count: 243 (19.014084%)	Total: 255 (19.953053%)
[0.100822, 0.102819)	    ################	Count: 1009 (78.951485%)	Total: 1264 (98.904541%)
[0.102819, 0.104816)	                    	Count: 9 (0.704225%)	Total: 1273 (99.608765%)
[0.104816, 0.106814)	                    	Count: 2 (0.156495%)	Total: 1275 (99.765259%)
[0.106814, 0.108811)	                    	Count: 1 (0.078247%)	Total: 1276 (99.843506%)
[0.108811, 0.110808]	                    	Count: 2 (0.156495%)	Total: 1278 (100.000000%)
I1102 19:10:40.236456 24648 rosbag_validate_main.cc:154] Time delta histogram for consecutive messages on topic "/scan" (frame_id: "velodyne"):
Count: 2556  Min: -0.100869  Max: 0.110808  Mean: 0.050430
[-0.100869, -0.079701)	                    	Count: 1 (0.039124%)	Total: 1 (0.039124%)
[-0.079701, -0.058534)	                    	Count: 0 (0.000000%)	Total: 1 (0.039124%)
[-0.058534, -0.037366)	                    	Count: 0 (0.000000%)	Total: 1 (0.039124%)
[-0.037366, -0.016198)	                    	Count: 0 (0.000000%)	Total: 1 (0.039124%)
[-0.016198, 0.004970)	          ##########	Count: 1276 (49.921753%)	Total: 1277 (49.960876%)
[0.004970, 0.026137)	                    	Count: 0 (0.000000%)	Total: 1277 (49.960876%)
[0.026137, 0.047305)	                    	Count: 0 (0.000000%)	Total: 1277 (49.960876%)
[0.047305, 0.068473)	                    	Count: 0 (0.000000%)	Total: 1277 (49.960876%)
[0.068473, 0.089640)	                    	Count: 0 (0.000000%)	Total: 1277 (49.960876%)
[0.089640, 0.110808]	          ##########	Count: 1279 (50.039124%)	Total: 2556 (100.000000%)

I am trying to get permission from my professor to upload the bag but I am not optimistic. Is there a way you can help me out with what I've got here?

Thank you!
-Calvin

**Comment by gaschler** [comment]
Hi Calvin,
thanks for sharing your fork. You can post the results of /devel_isolated/cartographer_ros/lib/cartographer_ros/cartographer_rosbag_validate 
In case this doesn't help, we would need to look at the bag file.

**Comment by Calvin4016** [comment]
Thanks for your prompt feedback. I was able to identify the issue and it was indeed a human error (caused by another node overwriting the correct tf and imu data) and not a Cartographer issue.

**Comment by letsbelopez** [comment]
@Calvin4016 I think we have a similar setup and I'm getting similar output when running the validate tool on my bag file. I don't have a IMU though, so I'm just using 2d options. 

Would you be able to explain what your solution was or if you could take a look at my issue #623  please?
