### ISSUE TITLE
Bad Output Results

### ISSUE THREAD

**Issue by athtest800** [googlecartographer/cartographer_ros#572]
Hello!
I try to implement cartographer ros in a rotating SICK laser but I cannot get it work.
Here is my link "https://github.com/athtest800/cartographer_ros"
I use my custom "demo_slam_3d.launch" file with the included "houses.bag" file in the bag folder.
Is there a solution? or the SICK laser, due to its low point density, is not suitable for cartographer?
Thank you.
Ath

**Comment by gaschler** [comment]
There are many Sick lasers with different resolutions, could you specify?
You started with the 3D algorithm, for this you need at least ~4 rows, more are better.
I'd recommend to start with the 2D algorithm first if your data permits.
