### ISSUE TITLE
Running bagfile with cartographer_ros

### ISSUE THREAD

**Issue by shahabty** [googlecartographer/cartographer_ros#586]
Hello,
I would like to run cartographer on my own videos files. I converted them into bag file. However, when I'm running the bagfile with backpack_2d launch file, rviz opens  and nothing happens.
I appreciate it if you could tell me how to write my own .launch and config files in order to run cartographer on my own bag files. 
Additional info: the data is RGB frames which I converted them to bagfile.

**Comment by SirVer** [comment]
This lacks a lot of information and in its current form is not actionable. 

Please run through our [issue template](https://github.com/googlecartographer/cartographer_ros/blob/master/.github/ISSUE_TEMPLATE) and reopen a new issue providing as much of the asked for information as possible. Especially your data and your configuration files are important.

**Comment by gaschler** [comment]
Hi Shahabty,
thanks for your interest in Cartographer.
_Cartographer requires range data_, RGB videos cannot be processed.
Please have a look at https://google-cartographer.readthedocs.io/en/latest/index.html
