### ISSUE TITLE
Get current odometry from ROS(question)

### ISSUE THREAD

**Issue by BoomFan** [googlecartographer/cartographer_ros#617]
Hi,

It might be a stupid question but I'm going to ask anyway.

I'm trying to run cartographer_ros in realtime with a 2D lidar and an IMU. It seems like cartographer_ros publishes the all the trajectory poses of my robot in topic `/trajectory_node_list`, but I actually cares more about my robot's current position than the whole trajectory.

Is there a topic that only contains my robot current odometry(pose, orientation, twist)?

Thanks for your help.

**Comment by gaschler** [comment]
Hi, the tf topic should publish, among others, the position of the frame base_link wrt to the map.
