### ISSUE TITLE
Unable to produce map (scan topic from rplidar not utilised by cartographer

### ISSUE THREAD

**Issue by JnusK** [googlecartographer/cartographer_ros#635]
Hi, sorry but I am a novice at ROS and cartographer and while trying to set up cartographer with a RPLIDAR A2, I encountered the issue where the /scan topic published by the rplidar_ros is not being used by cartographer_node. I think it might be an issue with my configuration files. Here are my files [Link](https://github.com/JnusK/cartographer_ros ).

**Comment by JnusK** [comment]
![rosgraph](https://user-images.githubusercontent.com/18348293/34360973-f2e43da8-eaa0-11e7-9490-24fc36af2a6d.png)
The rqt_graph

**Comment by JnusK** [comment]
Realised my issue was that scan should be remapped to base_link instead

**Comment by joyde3382** [comment]
Hey @JnusK I am having the exact same issue right now with an RPLidar a1. Are your config files up to date? I tried using the one you have in your github but it did not change anything. Also my rqt_graph looks exactly like yours. 

Any suggestions to what i might be missing? :)
