### ISSUE TITLE
Can't call the rosservice 

### ISSUE THREAD

**Issue by 915414922** [googlecartographer/cartographer_ros#640]
Greetings,cartographer team.I'm a new player in ros.

I found the API in the document can't be use when I installed the program according to the leading.
![Markdown](http://i2.bvimg.com/605993/43b1ddecf6e09a7b.png)

I install the cartographer twice and the problem never gone.(both 0.2 and 0.3 version).
I just install it and havn't change the launch and .lua.

Thank you,and if you can help I'll be very grateful.

PS:other rosservice is running correctly.
![test2](https://user-images.githubusercontent.com/22735158/34431624-a2872f3e-ecab-11e7-9231-d40e1a608830.PNG)

**Comment by ojura** [comment]
You need to `source` the `setup.bash` file, inside the `devel` folder of the workspace where you built Cartographer.

**Comment by 915414922** [comment]
Thank you very much.I solved it after souce the bash in devel_isolated folder,as I just sourced install_isolated folder before following the document.
