### ISSUE TITLE
Tuning Help required for Dual VLP16 and IMU setup

### ISSUE THREAD

**Issue by GeoBIMpro** [googlecartographer/cartographer_ros#650]
Hi,
I have a setup consisting two VLP16 scanners.
I am not able to tune proper parameters for my setup.
Below are the links for bag file and urdf:
Bag file: https://drive.google.com/file/d/19F1FkYd47ycefaxcSpYByEo8Q8p8jpx1/view?usp=sharing
URDF: https://gist.github.com/GeoBIMpro/ca1f0d5a29ad8a983ef13dd022c61746
backpack_3d Config: https://gist.github.com/GeoBIMpro/a24dd5f1cb701e43ff42e76f04c0aba5

Can someone help tuning my setup?

Thanks and Regards,
Vasanth

**Comment by gaschler** [comment]
Two VLP16 should be pretty similar to the default config.
Please give more details following the issue template https://raw.githubusercontent.com/googlecartographer/cartographer_ros/master/.github/ISSUE_TEMPLATE
specifically, the output of the bag file validate tool.
