### ISSUE TITLE
Is Benewake TFMini Lidar module compatible?

### ISSUE THREAD

**Issue by kibriashuvo** [googlecartographer/cartographer_ros#656]
Hello,

I bought a BW-TFMini LiDAR module. Here is the link of the product.

https://ozrobotics.com/shop/tfmini-lidar-distance-measurement-lidar-sensor-12m-for-drones-and-uav-robots/
I can pan the LIDAR up to 180 degrees with a Pan-Tilt kit along with a typical servo.

However, my question is that does the cartographer algorithm require a 360 degrees rotating LIDAR for creating 2D maps or 180 degree is ok?

Thank you.

**Comment by Entropy512** [comment]
I have had success using Cartographer with a SICK LMS100 that had a good portion of its view obstructed by the vehicle it was mounted to - approximately 200-220 degree FOV.

However, I'm pretty sure that by adding a rangefinder like that to a pan/tilt mechanism, you'll find issues with a combination of:
Spot size too large
Angle repeatability not good enough
Scan rate not high enough

**Comment by gaschler** [comment]
@Entropy512 thanks for the helpful answer.
I agree, 180 deg may be not ideal but you can tune it.

Closing as answered.

**Comment by kibriashuvo** [comment]
@Entropy512 Thanks for sharing your experience.

I will try to make something to rotate it 360 degrees and test if it works.
