### ISSUE TITLE
How to turn back_3d into 2d map

### ISSUE THREAD

**Issue by ytgcljj** [googlecartographer/cartographer_ros#670]
I have a VLP 16, and I can now see a multi line map of 3d, but there is no way to turn it into 2d map
The configuration files , launch file and urdf file is [here](https://github.com/ytgcljj/ndt_localizer)
Could you help me or give some hint? Thank you!

**Comment by ytgcljj** [comment]
bag file is here [](https://drive.google.com/open?id=14zntHzga-wpiCxHX4p8wLZEVdi1TsghL)

**Comment by ytgcljj** [comment]
![_20180116173738](https://user-images.githubusercontent.com/27713475/34981933-00b65a4e-fae4-11e7-8e8e-fa7597b9ff2b.jpg)

**Comment by cschuet** [comment]
@ytgcljj Are you running Cartographer?

**Comment by cschuet** [comment]
![image](https://user-images.githubusercontent.com/25035505/34982455-b76291c0-faaa-11e7-873f-ceaad2a152df.png)

**Comment by ytgcljj** [comment]
@cschuet  
yes  But our company's corridors and offices have become a mess map. I don't know where I'm wrong. There's another problem. This is the bag package that can be used. But I want to use laser directly. Why can't you use it? You can help me look at my configuration file. It's wrong.
Thank you for your reply

**Comment by ytgcljj** [comment]
![hector_2017_10_10-17_45_35](https://user-images.githubusercontent.com/27713475/34986794-dcc131e4-faf3-11e7-901d-20e80deea580.png)
