### ISSUE TITLE
How to make PGM a pbstream file and what order to enter, thank you

### ISSUE THREAD

**Issue by ytgcljj** [googlecartographer/cartographer_ros#672]
How to make PGM（ros map） a pbstream file and what order to enter, thank you
ros map file>>pbstream file

**Comment by ojura** [comment]
Not currently possible because it is not implemented. Pbstream is a full snapshot of Cartographer SLAM state, while PGM is only a picture. It is doable, but somebody would need to implement it, which is not trivial.

**Comment by ytgcljj** [comment]
thank you
