### ISSUE TITLE
VLP-16 3D map of underground garage

### ISSUE THREAD

**Issue by meng216073** [googlecartographer/cartographer_ros#675]
hi, I need help.
when I use cartographer_ros and VLD-16 to build map of underground garage, i can not get the map like the demo_backpack3d.
I use two LIDAR,  they are arranged on the front and back of my car. I drove three laps in the underground garage. And I record the data.
Then I run the code:
`roslaunch cartographer_ros demo_vlp16-imu-2lidar.launch bag_filename:=/home/gm/2018-1-15-17-24-cartographer-subway.bag`
The following is the result I got.
![image](https://user-images.githubusercontent.com/22534158/35264192-c7a1e034-0056-11e8-8d93-7cc5d8108231.png)
![image](https://user-images.githubusercontent.com/22534158/35264688-a8c39584-0058-11e8-8106-2f0425bafa5b.png)
![image](https://user-images.githubusercontent.com/22534158/35264698-b0f52fec-0058-11e8-8fb4-4e94e9fb8b68.png)
As you can see , the maps are not in the same plane. Can you tell me why? Closed loop detection can not be used in maps.
Looking forward to your reply! Thank you ~

**Comment by gaschler** [comment]
For a tuning issue, please give more details following the issue template https://raw.githubusercontent.com/googlecartographer/cartographer_ros/master/.github/ISSUE_TEMPLATE
specifically, the output of the bag file validate tool.
