### ISSUE TITLE
Unable to start my first real sick_tim sensor demo with cartographer.

### ISSUE THREAD

**Issue by jim1949** [googlecartographer/cartographer_ros#688]
Hi, I'm using sick_tim561, and I want to configure the lua and the launch file to run cartographer with my sensor. 
But it gives this error:
https://github.com/jim1949/cartographer_issue/blob/master/Start_demo/error_log.txt

Here is my sensor rosbag:
link: https://pan.baidu.com/s/1cPsxye
password: becb

My launch file:
https://github.com/jim1949/cartographer_issue/tree/master/Start_demo/demo_revo.launch

My lua configuration file:
https://github.com/jim1949/cartographer_issue/tree/master/Start_demo/revo_lds.lua

I have no idea how to solve this issue. Need some tips from your guys.

Thanks.

**Comment by gaschler** [comment]
You removed `include "trajectory_builder.lua"` from the master revo_lds.lua.
