### ISSUE TITLE
How to use lifelong mapping feature?

### ISSUE THREAD

**Issue by Oluwatoni** [googlecartographer/cartographer_ros#695]
I looked through the google group messages and it wasn't clear to me if lifelong mapping has been implemented. If it has, how do I enable it for a robot running ROS?
@
Thank you!

**Comment by guilhermelawless** [comment]
See at the bottom of https://github.com/googlecartographer/cartographer/projects

**Comment by gaschler** [comment]
So far, the only part of the lifelong mapping feature that has been implemented is trimming arbitrary submaps from the pose graph. To use this, you need to implement a class derived from `mapping::PoseGraphTrimmer`.
This is not exposed to Ros.

(Closing as answered.)

**Comment by musi00** [comment]
Does thi mean that cartographer's map currently grows infinitely if there is no submap deletion in place
