### ISSUE TITLE
Memory overflow

### ISSUE THREAD

**Issue by 915414922** [googlecartographer/cartographer_ros#697]
If I run cartographer receiving data online more than 20mins ,the memory will overflow and all the program would die.I guess it's the submap blocked in the memory.
Did you have this case before?
How can I clean the submaps in memory?
I am grateful if you can help.

**Comment by gaschler** [comment]
The only mode that should use limited memory is *pure localization* (see tuning documentation).
If you want to reduce memory usage in general, use the 2D pipeline or increase the filter settings and voxel sizes, or both.

(Closing as answered.)

**Comment by 915414922** [comment]
Thanks
