### ISSUE TITLE
use proto2 and proto3

### ISSUE THREAD

**Issue by weisongwen** [googlecartographer/cartographer_ros#698]
Thanks for your effort on this great package,

I used this newest version of package and updated the proto 2 to proto 3 (proto 3 is needed for newest version of cartographer ). as a result, some of my personal package need proto 2 and can not work with proto 3.

do you have any suggestion on this issue?

**Comment by gaschler** [comment]
Please find my and kdaun's answers in https://github.com/googlecartographer/cartographer_ros/issues/625
You can install protobuf in `catkin_ws/install_isolated` and not touch your system.
Here is another related issue: https://github.com/googlecartographer/cartographer/issues/674
