### ISSUE TITLE
Cartographing 2D with VLP16 Hires without IMU

### ISSUE THREAD

**Issue by KevinRiehl** [googlecartographer/cartographer_ros#725]
Dear community,
I am working with Ubuntu 16.04.03 and ROS kinetic.
I installed googlecartographer and the DEMOs work fine.
Furthermore I installed the velodyne drivers and I can see
the pointcloud etc.

I now want to combine these two things, in order to cartograph
with my VLP16 Hires and Google Cartographer 2D.

http://google-cartographer-ros.readthedocs.io/en/latest/index.html
Following the link above, one can use the cartographer 2D without 
an IMU. All examples provided do use bag files with IMU data.

**Can you show me an example of how to use this great cartograph software without IMU data?** 

How to do that? I tried to change the launch files and lua files, to deactivate
SLAM and to activate RealTimeCorrelativeScanMatcher, but I dont know how to!

The tries I managed so far end up in not working due to missing tfs. No node is publishing tfs. 

Thank you very much,
Sincerely yours, Kevin Riehl

**Comment by gaschler** [comment]
TRAJECTORY_BUILDER_2D.use_imu_data = false

**Comment by KevinRiehl** [comment]
Okay. This does not work. There is a problem with tf I guess.

This is my Console output:
[console.txt](https://github.com/googlecartographer/cartographer_ros/files/1731527/console.txt)

This is my lua file: 
[backpack_2d.lua.txt](https://github.com/googlecartographer/cartographer_ros/files/1731529/backpack_2d.lua.txt)

This is a screenshot:
![bildschirmfoto vom 2018-02-16 14-29-17](https://user-images.githubusercontent.com/36194371/36310537-aca611a8-1328-11e8-896c-171f0a7bc0bd.png)

This are my launch files:
[backpack_2d.launch.txt](https://github.com/googlecartographer/cartographer_ros/files/1731546/backpack_2d.launch.txt)
[demo_backpack_2d.launch.txt](https://github.com/googlecartographer/cartographer_ros/files/1731547/demo_backpack_2d.launch.txt)


I am calling "roslaunch cartographer_ros demo_backpack_2d.launch".
I compiled my catkin_ws multipletimes after changes.

There seem to be problems with tf.

The topic "/scan" is posted on a frame called "/map". What am I doing wrong?
Thanks, Kevin

**Comment by gaschler** [comment]
> The topic "/scan" from my velodyne is posted on a frame called "/map". What am I doing wrong?

Remap from scan to map in the launch file?

**Comment by KevinRiehl** [comment]
No you misunderstood me. The topic "/scan" is published with the name "/scan".
Echoing with `rostopic echo /scan ` delivers that it is in frame "/map".

`header: 
  seq: 13
  stamp: 
    secs: 1518790467
    nsecs: 983551000
  frame_id: "map"
angle_min: -3.14159274101
angle_max: 3.14159274101
angle_increment: 0.00700000021607
time_increment: 0.0
scan_time: 0.0
range_min: 0.0
range_max: 200.0
ranges: [3.1577866077423096, 3.14778733253479, 3.139787435531616, 3.1497867107391357, 3.1377878189086914, 3.1537864208221436, 3.1377878189086914, 3.143787145614624, 3.1377878189086914, 3.1317882537841797, 3.1497867107391357, 3.139787435531616, 3.141787528991699, 3.147787094116211, 3.1357877254486084, 3.1517865657806396, 3.145787239074707, 3.1537864208221436, 3.1497867107391357, 3.145787239074707, 3.165785789489746, 3.1597859859466553, 3.1557865142822266, 3.16778564453125, 3.1617860794067383, 3.1617860794067383, 3.171785354614258, 3.1757850646972656, 3.1857845783233643, 3.1757850646972656, 3.1957833766937256, 2.943801164627075, 2.945800304412842, 2.901803731918335, 2.8978042602539062, 2.9498002529144287, 3.189784049987793, 3.213782548904419, 3.2177822589874268, 3.209782600402832, 3.233781337738037, 3.2217822074890137, 3.2257814407348633, 3.233781337738037, 3.235781192779`

Even though I added the line:
`	<remap from="scan" to="map"/>`
to "demo_backpack_2d.launch"

Nothing changes...problem stays the same...

Using "rosrun tf tf_monitor" we can see...that no tf at all is there.

**Comment by gaschler** [comment]
Frame "map" is not ideal because cartographer_ros usually publishes under this frame.
You can edit the frame names in the lua configuration.
It also needs to match with the urdf model.

**Comment by KevinRiehl** [comment]
Thank you very much, I could now solve the problem.
The frame that my velodyne driver should post to is called
"horizontal_laser_link".

For all those, who are interested in the solution, the following
files contain all configurations to use the VLP 16 without IMU:

Launch Files in package "cartographer_ros":
[VELbackpack_2d.launch.txt](https://github.com/googlecartographer/cartographer_ros/files/1736244/VELbackpack_2d.launch.txt)
[VELdemo_backpack_2d.launch.txt](https://github.com/googlecartographer/cartographer_ros/files/1736245/VELdemo_backpack_2d.launch.txt)

LUA Files in package "cartographer" and "cartographer_ros":
[velobackpack_2d2.lua.txt](https://github.com/googlecartographer/cartographer_ros/files/1736250/velobackpack_2d2.lua.txt)
[velomap_builder.lua.txt](https://github.com/googlecartographer/cartographer_ros/files/1736251/velomap_builder.lua.txt)
[velotrajectory_builder.lua.txt](https://github.com/googlecartographer/cartographer_ros/files/1736252/velotrajectory_builder.lua.txt)
[velotrajectory_builder_2d.lua.txt](https://github.com/googlecartographer/cartographer_ros/files/1736253/velotrajectory_builder_2d.lua.txt)

Launch Files in package "velodyne_points":
[VLP16_HiRes_points.launch.txt](https://github.com/googlecartographer/cartographer_ros/files/1736249/VLP16_HiRes_points.launch.txt)

Kind regards,
Kevin Riehl

**Comment by xukuanHIT** [comment]
@KevinRiehl 
Hi,  I met the same problem as you, and I am glad to see that you have solved it. I looked at your answer carefully, and changed 4 Lua and 2 launch files according to your prompt.The results after the compilation run are as follows：
[FATAL] [1528900046.641877316]: F0613 22:27:26.000000 29707 lua_parameter_dictionary.cc:399] Check failed: HasKey(key) Key 'grid_options_2d' not in dictionary:
{
  num_range_data = 35.000000,
  range_data_inserter = {
    hit_probability = 0.550000,
    insert_free_space = true,
    miss_probability = 0.490000,
  },
  resolution = 0.050000,
}
So I changed the file as follows：
  submaps = {
    resolution = 0.05,
    num_range_data = 90,
    grid_options_2d=false,
    range_data_inserter = {
      insert_free_space = true,
      hit_probability = 0.55,
      miss_probability = 0.49,
      

[ INFO] [1528899340.824396059]: I0613 22:15:40.000000 28690 configuration_file_resolver.cc:41] Found '/home/bryant/catkin_ws/install_isolated/share/cartographer_ros/configuration_files/velobackpack_2d2.lua' for 'velobackpack_2d2.lua'.
[ INFO] [1528899340.824629976]: I0613 22:15:40.000000 28690 configuration_file_resolver.cc:41] Found '/home/bryant/catkin_ws/install_isolated/share/cartographer_ros/configuration_files/velomap_builder.lua' for 'velomap_builder.lua'.
[ INFO] [1528899340.824667907]: I0613 22:15:40.000000 28690 configuration_file_resolver.cc:41] Found '/home/bryant/catkin_ws/install_isolated/share/cartographer_ros/configuration_files/velomap_builder.lua' for 'velomap_builder.lua'.
[ INFO] [1528899340.824724828]: I0613 22:15:40.000000 28690 configuration_file_resolver.cc:41] Found '/home/bryant/catkin_ws/install_isolated/share/cartographer/configuration_files/pose_graph.lua' for 'pose_graph.lua'.
[ INFO] [1528899340.824756388]: I0613 22:15:40.000000 28690 configuration_file_resolver.cc:41] Found '/home/bryant/catkin_ws/install_isolated/share/cartographer/configuration_files/pose_graph.lua' for 'pose_graph.lua'.
[ INFO] [1528899340.824859762]: I0613 22:15:40.000000 28690 configuration_file_resolver.cc:41] Found '/home/bryant/catkin_ws/install_isolated/share/cartographer_ros/configuration_files/velotrajectory_builder.lua' for 'velotrajectory_builder.lua'.
[ INFO] [1528899340.824889941]: I0613 22:15:40.000000 28690 configuration_file_resolver.cc:41] Found '/home/bryant/catkin_ws/install_isolated/share/cartographer_ros/configuration_files/velotrajectory_builder.lua' for 'velotrajectory_builder.lua'.
[ INFO] [1528899340.824938652]: I0613 22:15:40.000000 28690 configuration_file_resolver.cc:41] Found '/home/bryant/catkin_ws/install_isolated/share/cartographer_ros/configuration_files/velotrajectory_builder_2d.lua' for 'velotrajectory_builder_2d.lua'.
[ INFO] [1528899340.824967197]: I0613 22:15:40.000000 28690 configuration_file_resolver.cc:41] Found '/home/bryant/catkin_ws/install_isolated/share/cartographer_ros/configuration_files/velotrajectory_builder_2d.lua' for 'velotrajectory_builder_2d.lua'.
[ INFO] [1528899340.825050086]: I0613 22:15:40.000000 28690 configuration_file_resolver.cc:41] Found '/home/bryant/catkin_ws/install_isolated/share/cartographer/configuration_files/trajectory_builder_3d.lua' for 'trajectory_builder_3d.lua'.
[ INFO] [1528899340.825081111]: I0613 22:15:40.000000 28690 configuration_file_resolver.cc:41] Found '/home/bryant/catkin_ws/install_isolated/share/cartographer/configuration_files/trajectory_builder_3d.lua' for 'trajectory_builder_3d.lua'.
F0613 22:15:40.825194 28690 lua_parameter_dictionary.cc:116] Check failed: lua_istable(L, -1) Topmost item on Lua stack is not a table!
[FATAL] [1528899340.825342131]: F0613 22:15:40.000000 28690 lua_parameter_dictionary.cc:116] Check failed: lua_istable(L, -1) Topmost item on Lua stack is not a table!
*** Check failure stack trace: ***
    @     0x7fca67c23daa  (unknown)
    @     0x7fca67c23ce4  (unknown)
    @     0x7fca67c236e6  (unknown)
    @     0x7fca67c26687  (unknown)
    @           0x5f647f  cartographer::common::(anonymous namespace)::CheckTableIsAtTopOfStack()
    @           0x5f7cdb  cartographer::common::LuaParameterDictionary::PopDictionary()
    @           0x5f9028  cartographer::common::LuaParameterDictionary::GetDictionary()
    @           0x5df831  cartographer::mapping::CreateSubmapsOptions2D()
    @           0x5d6abf  cartographer::mapping::CreateLocalTrajectoryBuilderOptions2D()
    @           0x5d5cb3  cartographer::mapping::CreateTrajectoryBuilderOptions()
    @           0x5d3a12  cartographer_ros::CreateTrajectoryOptions()
    @           0x599230  cartographer_ros::LoadOptions()
    @           0x596e83  cartographer_ros::(anonymous namespace)::Run()
    @           0x5940d6  main
    @     0x7fca640a2f45  (unknown)
    @           0x596cd7  (unknown)
    @              (nil)  (unknown)
[cartographer_node-2] process has died [pid 28690, exit code -6, cmd /home/bryant/catkin_ws/install_isolated/lib/cartographer_ros/cartographer_node -configuration_directory /home/bryant/catkin_ws/install_isolated/share/cartographer_ros/configuration_files -configuration_basename velobackpack_2d2.lua __name:=cartographer_node __log:=/home/bryant/.ros/log/e8ae4e78-6f11-11e8-abe3-3497f693bf66/cartographer_node-2.log].
log file: /home/bryant/.ros/log/e8ae4e78-6f11-11e8-abe3-3497f693bf66/cartographer_node-2*.log

Now there is an error, and I checked a lot of information and did not know how to solve it. I am a novice programmer. I would be very grateful if you could give me some suggestions.

**Comment by nightheronry** [comment]
Hi, 
I use the [code](https://github.com/googlecartographer/cartographer_ros/issues/725#issuecomment-366642781) contributed by @KevinRiehl . And I also get the same error like @xukuanHIT .  Could someone please give me some advice?
Detail are as follows:

`F0917 23:14:02.553182 15188 lua_parameter_dictionary.cc:399] Check failed: HasKey(key) Key 'grid_options_2d' not in dictionary:
{
  num_range_data = 35.000000,
  range_data_inserter = {
    hit_probability = 0.550000,
    insert_free_space = true,
    miss_probability = 0.490000,
  },
  resolution = 0.050000,
}
[FATAL] [1537197242.553567581]: F0917 23:14:02.000000 15188 lua_parameter_dictionary.cc:399] Check failed: HasKey(key) Key 'grid_options_2d' not in dictionary:
{
  num_range_data = 35.000000,
  range_data_inserter = {
    hit_probability = 0.550000,
    insert_free_space = true,
    miss_probability = 0.490000,
  },
  resolution = 0.050000,
}
*** Check failure stack trace: ***
    @     0x7f14d7dc1daa  (unknown)
    @     0x7f14d7dc1ce4  (unknown)
    @     0x7f14d7dc16e6  (unknown)
    @     0x7f14d7dc4687  (unknown)
    @           0x5e259f  cartographer::common::LuaParameterDictionary::CheckHasKey()
    @           0x5e25ed  cartographer::common::LuaParameterDictionary::CheckHasKeyAndReference()
    @           0x5e288e  cartographer::common::LuaParameterDictionary::GetDictionary()
    @           0x6dad21  cartographer::mapping::CreateSubmapsOptions2D()
    @           0x682acf  cartographer::mapping::CreateLocalTrajectoryBuilderOptions2D()
    @           0x5e7c33  cartographer::mapping::CreateTrajectoryBuilderOptions()
    @           0x5d4492  cartographer_ros::CreateTrajectoryOptions()
    @           0x5d3d60  cartographer_ros::LoadOptions()
    @           0x596e83  cartographer_ros::(anonymous namespace)::Run()
    @           0x5940d6  main
    @     0x7f14d423cf45  (unknown)
    @           0x596cd7  (unknown)
    @              (nil)  (unknown)
[cartographer_node-3] process has died [pid 15188, exit code -6, cmd /home/slam/catkin_ws/install_isolated/lib/cartographer_ros/cartographer_node -configuration_directory /home/slam/catkin_ws/install_isolated/share/cartographer_ros/configuration_files -configuration_basename velobackpack_2d2.lua __name:=cartographer_node __log:=/home/slam/.ros/log/4f024ab0-ba8c-11e8-aaef-1c6f659f55c1/cartographer_node-3.log].
log file: /home/slam/.ros/log/4f024ab0-ba8c-11e8-aaef-1c6f659f55c1/cartographer_node-3*.log

`

**Comment by gaschler** [comment]
The config syntax was changed so we can support the truncates signed distance field (TSDF) feature.

This change was made in https://github.com/googlecartographer/cartographer/pull/1108/files#diff-b612d6fd6de960e1b7974146d059f2fb

Please adapt your config accordingly.
