### ISSUE TITLE
cannot compile actual master

### ISSUE THREAD

**Issue by TobiMiller** [googlecartographer/cartographer_ros#730]
for me it is not possible to compile the master. i switched cartographer and cartographer_ros to tags/0.3.0 and it compiles. so i think it is not a dependency problem by my side.

i have compiled proto3 as described on its git. i have pulled cartographer, cartographer_ros,  ceres with rosinstall file into my new ros workspace. i have installed the dependecies with rosdep install --from-paths. 
then i used catkin build & tried the compile commands from your script (removed install space because i have no rights to compile into /opt/):
`export BUILD_FLAGS="--use-ninja --install"
catkin_make_isolated ${BUILD_FLAGS} $@`

**CATKIN BUILD ERROR:**
![cartographer_compile_error_catkin_build](https://user-images.githubusercontent.com/32275/36529970-22e1c08e-17ba-11e8-9700-0a3e85436c64.png)

**CATKIN MAKE ERROR:**
![cartographer_compile_error_catkin_make](https://user-images.githubusercontent.com/32275/36529971-22fb0d32-17ba-11e8-9603-6a960817f48c.png)

**Comment by cschuet** [comment]
We did some refactorings. Could it be that your build directories are stale? Try

```
rm -Rf *isolated
```

**Comment by cschuet** [comment]
Please reopen if that does not solve it.

**Comment by TobiMiller** [comment]
nope. same like here
https://github.com/googlecartographer/cartographer_ros/issues/733

**Comment by cschuet** [comment]
Duplicate of #733

Thanks for the report. Let's use #733 to track it.
