### ISSUE TITLE
2D Cartographer with only one LIDAR and one IMU

### ISSUE THREAD

**Issue by jediofgever** [googlecartographer/cartographer_ros#731]
Hi There, 

I have searched around existing issues to find a answer for my question however I could not find some useful info, so please forgive me if this is already asked before. I have only one LIDAR that I would like to use with 2D Cartographer. I know that in Demos the bag files are recorded with 2 LIDARS, so when I record bag file with one LIDAR and one IMU it shows nothing on Rviz, 

WhaT part of code should be modified in order to be able to run the bag file I recorded with one LIDAR and IMU ?

Thank you !

**Comment by ojura** [comment]
The second lidar (vertical laser) is not used at all during SLAM. Your problem lies somewhere else. Most basic problems are wrong frame names and topic remappings, make sure you got that right.

**Comment by jediofgever** [comment]
Hi, @ojura 
Here is a screenshot  of my frames, Can you post your frames result so that I can compare where I got wrong?
![a](https://user-images.githubusercontent.com/18460336/36542503-f0e5e3d2-181b-11e8-8eca-4d77c4dd7c94.png)

**Comment by ojura** [comment]
What is your tracking frame in cartographer? Is it `base_link`? You need a transform from it to the imu and laser_mount_link frames. Your tf tree has to be connected.

**Comment by jediofgever** [comment]
Okay I think I understand where problem lays now. I am closing the issue, however I will comment if cannot get it work :) . Thanks for your help !
