### ISSUE TITLE
Which IMU and LIDAR models were used to collect 2D demo 

### ISSUE THREAD

**Issue by jediofgever** [googlecartographer/cartographer_ros#757]
Hi there, 
As stated in title I want to know which hardware used to collect demo data for 2D slam. I have an IMU but it gives me only acceleration (orientational ,translational), [this](https://shop.xsens.com/shop/mti-10-series/mti-10-imu/mti-10-imu-2a8g4-dk) is my IMU, can this be used for 2D google cartographer ?

**Comment by gaschler** [comment]
2D does not require IMU data.
If IMU data is input, only angular velocity and the direction of gravity acceleration is used.

(Closing as answered.)
