### ISSUE TITLE
write_state hangs forever for ROS <=> gRPC bridge

### ISSUE THREAD

**Issue by cschuet** [googlecartographer/cartographer_ros#763]
When running the Cartographer online ROS <=> gRPC bridge and cartographer_grpc in SLAM mode and then issuing a /finish_trajectory ROS service call and then a /write_state against it, write_state hangs forever. Maybe the WriteState gRPC method is still broken?

**Comment by pifon2a** [comment]
I have launched it with:

```
roslaunch cartographer_ros grpc_demo_backpack_2d.launch    bag_filename:=${HOME}/workspace/bags/b2-2016-04-27-12-31-41.bag 
```
and it managed to die after it has built the map with 
` pose_graph_stub.cc:70] Check failed: client.Write(request) `

**Comment by pifon2a** [comment]
https://github.com/googlecartographer/cartographer/pull/973
