### ISSUE TITLE
Regression: build jobs fail

### ISSUE THREAD

**Issue by MichaelGrupp** [googlecartographer/cartographer_ros#769]
Hi guys,

you're probably already aware of this, but the CI jobs of `cartographer_ros` and all dependent `cartographer_*` repos fail due to the recent API changes without follow-ups in `cartographer_ros`. Consequently the CQ pipeline will fail too I guess. @pifon2a 

Not super urgent from my side, I just got a notification from our daily build of `cartographer_magazino`.

**Comment by pifon2a** [comment]
I am on it. Thanks.

--
Best regards,
Alexander Belyaev
+49 173 2950331

Google Germany GmbH
Erika-Mann-Straße 33
80636 München

Geschäftsführer: Paul Manicle, Halimah DeLaine Prado

**Comment by pifon2a** [comment]
Surprisingly enough, this is caused not by the API changes. One problem is gmock/gtest problems with catkin. @gaschler has already provided a fix. (https://github.com/googlecartographer/cartographer_ros/pull/768).

**Comment by MichaelGrupp** [comment]
Ok, I changed the title ;) You can close this then.
