### ISSUE TITLE
how to cite google cartographer on a paper

### ISSUE THREAD

**Issue by elgarbe** [googlecartographer/cartographer_ros#799]
I'm writing a paper about the design, construction and some test of an ASV.
One of the test is to make a map using google cartographer using ROS. I would like to make a cite to this work. Is there a paper, presentation or something else that I can use to cite to google cartogrpaher work?

Thank

**Comment by cschuet** [comment]
"Real-Time Loop Closure in 2D LIDAR SLAM" is the right paper to cite. Thanks.
