### ISSUE TITLE
catkin_make installation error

### ISSUE THREAD

**Issue by hiseholuwa** [googlecartographer/cartographer_ros#844]
Hi,
I was trying to get the ros_cartographer installed on an SBC that's being used for a SLAM project. During the catkin_make installation, I encountered the following errors:
```
..cartographer_ros/cartographer_ros/cartographer_ros/ros_map_writing_points_processor.h:24:77: fatal error:
cartographer/mapping/2d/proto/range_data_inserter_options_2d.pb.h: No such file or directory
compilation terminated.

```
I checked the folder based on the error and discovered that the file 'range_data_inserter_options_2d.pb.h' does not exit in the specified folder even though it is an include file in the 'ros_map_writing_points_processor.h" fille. I have deleted the files and downloaded over and over again to see if the files were missing by chance but I got the same error every single time. I'll appreciate any help in resolving this. Thanks

**Comment by Chambana** [comment]
repeat of #843

**Comment by hiseholuwa** [comment]
Thanks!
