### ISSUE TITLE
Where are the best tutorials?

### ISSUE THREAD

**Issue by mkhansen-intel** [googlecartographer/cartographer_ros#853]
I have seen some old tutorials that explain how to install and play back the bag files from a pre-recorded SLAM session, but haven't seen any tutorials on how to get it running with the rest of the Navigation stack. For instance, how do you send a destination? Also, when generating the map, do you have to use a manual control (like a joystick or wiimote) or does the robot explore on its own? I'm sorry if this is documented somewhere, I haven't been able to find it so please point me to where this is documented. Thanks!

**Comment by MichaelGrupp** [comment]
It's a pure SLAM system, i.e. it offers no navigation or path planning features. But you can use the maps and localization poses of Cartographer as an input for a navigation stack that builds on top of it (we at Magazino are doing this for example).

Regarding generating the map: Cartographer is versatile system that consumes certain types of input data for mapping & localization, but is pretty much agnostic to how this input data is collected. Whether you record that data by manual robot control, an exploration algorithm, with a handheld device etc. is completely up to you.

**Comment by mkhansen-intel** [comment]
@MichaelGrupp - Thank you for your response. I understand now, thanks for making it clear. I am surprised that no one has posted any tutorials on using it with other packages such as the ROS Nav stack, or the Explore package. Seems like it would be useful to many people using cartographer for the first time (like me).  Thanks again!

**Comment by MichaelGrupp** [comment]
I'm not aware of such tutorials or showcases, maybe someone from the maintainers knows? @cschuet

**Comment by cschuet** [comment]
@mkhansen-intel @MichaelGrupp Currently I am also not aware of any. But if someone was willing to write one, we'd be happy to host them on our read-the-docs page :)
