### ISSUE TITLE
running error with one Lidar and a imu 

### ISSUE THREAD

**Issue by coldrainy** [googlecartographer/cartographer_ros#868]
Hi,I got problems when running the cartographer_ros with my own 3d 16-laser lidar and one IMU rosbag data.Here are the details.
1.The rosbag_validate result link is [here](https://gist.github.com/coldrainy/a06027e37c9a23e4c0db16e115381cb2).
2.My configuration and launch and URDF files are [here](https://github.com/coldrainy/carto_configfiles.git).

I can successfully run the program.But there was no map generated and the /scan_matched_points2 look like the picture below.So what is the problem and what should I do to fix it?

![image](https://user-images.githubusercontent.com/20240108/40097054-9e9f0c58-5906-11e8-98ca-07027d439107.png)
![image](https://user-images.githubusercontent.com/20240108/40097081-b706b98a-5906-11e8-9f2c-5c8a7e847935.png)

**Comment by kentsommer** [comment]
A couple things to check:
* `TRAJECTORY_BUILDER_3D.num_accumulated_range_data = 160` should likely be set to `1` or `2` in your case if your `rs_lider` driver is publishing a full rotation per `PointCloud2` message. 
* Your URDF is almost certainly incorrect (specifically the orientation of the IMU). Your linear acceleration  is way off (`Average IMU linear acceleration is 1.84624 m/s^2, expected is [9.5, 10.5] m/s^2`) which likely means the URDF does not match the real world orientation of your IMU.

**Comment by coldrainy** [comment]
@kentsommer Thank you!I fixed the parameter that you point out and it worked!

**Comment by Duke-Allen** [comment]
@coldrainy @kentsommer 
Hello, I also got the problem when running cartographer with IMU and 16-lines lidar.
The rosbag_validate result is:
![2019-02-22 18-26-31](https://user-images.githubusercontent.com/45333787/53251264-3a08fb80-36f7-11e9-9628-db67f634f374.png)
My data bag:
![2019-02-21 11-40-49](https://user-images.githubusercontent.com/45333787/53251349-60c73200-36f7-11e9-9bf0-c15b884c7753.png)
I could not run the cartographer and there is no map build
![2019-02-22 13-30-54](https://user-images.githubusercontent.com/45333787/53251667-227e4280-36f8-11e9-9aa2-703b185dc1b5.png)
![2019-02-22 13-29-45](https://user-images.githubusercontent.com/45333787/53252154-3bd3be80-36f9-11e9-85eb-f226a475c88b.png)
my files:
[demo_rslidar_3d.launch](https://github.com/Duke-Allen/cartographer-configuration.git)
[mydemo_3d.rviz](https://github.com/Duke-Allen/cartographer-configuration.git)
[rslidar_2d.urdf](https://github.com/Duke-Allen/cartographer-configuration.git)
[rslidar_scan_3d.lua](https://github.com/Duke-Allen/cartographer-configuration.git)
[rslidar_3d.launch](https://github.com/Duke-Allen/cartographer-configuration.git)
Can you help me in this?

**Comment by Duke-Allen** [comment]
@kentsommer @coldrainy 
Hi, I have been running 3D cartographer successfully with no error by a 16-lines LIDAR and a MPU6050. But the track is inconsistent with the real movement, like this:
![rviz_screenshot_2019_03_16-10_51_11](https://user-images.githubusercontent.com/45333787/54470538-7c989200-47e4-11e9-83c3-98b0ce45a54d.png)

Here is my [bag](https://share.babel.cc/share.do?s=4553105679638233). 
The account: 15838868117
Password: 123456789
