### ISSUE TITLE
How to product cartographer_occupancy_grid_node ?

### ISSUE THREAD

**Issue by hoppss** [googlecartographer/cartographer_ros#873]
Hi,
I am new to cartographer, i create  a ws for cartographer and build it successful .

I want to know ,whether cartographer_ros will product a node named "cartographer_occupancy_grid_node "?

There is only a node named cartographer_node, what should i do to buiid this node ?

**Comment by MichaelGrupp** [comment]
This should have been built from your workspace, too.

If `rosrun cartographer_ros cartographer_occupancy_grid_node --help` shows the help for the command line parameters, you should be fine.

**Comment by cschuet** [comment]
Closing as answered. Please reopen if you have further questions.
