### ISSUE TITLE
cartographer takes up 100 and maps disorderly

### ISSUE THREAD

**Issue by ytgcljj** [googlecartographer/cartographer_ros#884]
I see that cartographer occupies more than 100 of CPU. The map is messy. Please help me analyze it. Thank you.

**Comment by ytgcljj** [comment]
![2018-05-30 19-05-45](https://user-images.githubusercontent.com/27713475/40717909-a3420856-6440-11e8-9672-f8769a823a59.png)
![2018-05-30 19-03-47](https://user-images.githubusercontent.com/27713475/40717952-c394fc12-6440-11e8-84c6-12222d41644d.png)

**Comment by bill4u** [comment]
Hello, I have encountered the same problem. Any suggestions? THX!
