### ISSUE TITLE
internal compiler error: Segmentation fault

### ISSUE THREAD

**Issue by RichardYao1995** [googlecartographer/cartographer_ros#911]
when I try to install cartographer on Jetson TX1, it turns out an error like below: 

/usr/local/include/eigen3/Eigen/src/Core/TriangularMatrix.h:915:9: internal compiler error: Segmentation fault
         kernel.assignDiagonalCoeff(i++);
         ^
Please submit a full bug report,

wish a solution from you. thanks a lot

**Comment by gaschler** [comment]
For a segfault, please re-compile with debug symbols, run first the tests and then your setup in a debugger and post stack traces.

**Comment by SirVer** [comment]
Very likely out of memory in the compiler.

**Comment by cschuet** [comment]
Closing as answered. Please reopen if you have further questions / can provide further details.
