### ISSUE TITLE
format for initial pose in launch file

### ISSUE THREAD

**Issue by dan9thsense** [googlecartographer/cartographer_ros#915]
I am unable to find documentation on how to format the initial pose option in a launch file.  Looking through issues, I pieced together this launch file, but it fails with this error:
`ERROR: unknown command line flag 'initial_pose'`

Can you point me to the documentation of how to set the initial pose option?
```
<launch>

  <node name="cartographer_node" pkg="cartographer_ros"
      type="cartographer_node" args="
          -configuration_directory $(find cartographer_ros)/configuration_files
          -configuration_basename myBot_localization.lua
          -load_state_filename ~/cartographer/maps/cart_with_odom_and_xsens_imu_dell.bag.pbstream
          -initial_pose { to_trajectory_id=0, relative_pose={translation={-0.9, -0.1, 0.0},rotation={0.0,0.0,0.1} }}"
      output="screen">
  </node>

</launch>
```

**Comment by gaschler** [comment]
`initial_pose` is only available through the `start_trajectory` executable.
So you can call that executable directly `rosrun cartographer_ros cartographer_start_trajectory`.
More details are the in [PR where initial_pose was introduced](https://github.com/googlecartographer/cartographer_ros/issues/579#issuecomment-351482589).

Currently, it is not available as an argument in the ROS service `StartTrajectory.srv` (one could call this a missing feature).

**Comment by dan9thsense** [comment]
Thanks for responding.  Is this right?  What do the ... refer to in the rosrun start_trajectory?
Is there no actual documentation for this feature/

Start cartographer node in pure localization mode. By default the map trajectory ID is 0 and the node automatically starts a new one (ID 1)

call /finish_trajectory for ID 1

rosrun cartographer_ros cartographer_start_trajectory ... -initial_pose '{to_trajectory_id = 0, relative_pose = { translation = { 0., 0., 0. }, rotation = { 0., 0., 0., } } }'.

**Comment by dan9thsense** [comment]
After a bunch of trial and error, discovered that the "..." corresponds to specifying the config directory and configuration basename.  Here is a complete example.  Fill in your own values for  the config directory and configuration basename.
```
rosservice call /finish_trajectory 1
rosrun cartographer_ros cartographer_start_trajectory  -configuration_directory <path to your cartographer_ros configuation files directory> -configuration_basename <name of your config (.lua) file> -initial_pose '{to_trajectory_id = 0, relative_pose = { translation = { 0., 0., 0. }, rotation = { 0.0, 0.0, 0.0 } } }'
```
