### ISSUE TITLE
Motion filter

### ISSUE THREAD

**Issue by athtest800** [googlecartographer/cartographer_ros#94]
Hello,
I get this `Motion filter reduced the number of scans to -nan%.`
I am using a rotating hokuyo laser that makes one rotation every 4 seconds.
How can solve this problem?

**Comment by damonkohler** [comment]
The log statement is admittedly confusing. There's no issue though; working as intended. It just hasn't filtered any scans yet and so it's a divide by 0. I'll put a PR together.

**Comment by athtest800** [comment]
Thank you
