### ISSUE TITLE
cartographer demo error

### ISSUE THREAD

**Issue by Jin-S-Kim** [googlecartographer/cartographer_ros#942]
Hello I want to slam with cartographer but I don't have robot like kobuki right now.
So I run demo file 'cartographer_paper_deutsches_museum.bag' and It works well. 
But I can't run other bag file. In Rviz Global Ststueand Robot Model have error. But I don't know how can I solve it. I run 2d and 3d 

This is bag file link that I can't run with cartographer demo.
https://drive.google.com/drive/folders/1bH6zeZxr3FVK42jb-SwQfM4tFKuzfsEU

**Comment by cschuet** [comment]
You have to make sure that the launch and lua file configuration match the data in the bag. Mostly you have to make sure two things

1. The topics in the rosbag match the topics that the launch and configuration is expecting.
2. Cartographer must be able to transform all incoming sensor data into the tracking frame. Tracking frame and each sensor data packet have a frame_id and you must provide the system with the information how to transform between those frames - either by a urdf or by the appropriate messages in the TF topic of your bag.
