### ISSUE TITLE
Global SLAM vs Local SLAM

### ISSUE THREAD

**Issue by SubMishMar** [googlecartographer/cartographer_ros#967]
Hi,
I have a conceptual doubt. Let us consider the following scenario.
I set` POSE_GRAPH.optimize_every_n_nodes = 100`
and `TRAJECTORY_BUILDER_2D.submaps.num_range_data = 1e11`

i.e. by setting the second parameter very high, I make sure that in my environment there is only one submap which coincides with the global map. I do so because, for the moment, I just want to concern myself with Local SLAM.

How is  ` POSE_GRAPH.optimize_every_n_nodes `  going to affect the overall pipeline? If I set this 0 then it means I am not doing any global slam and just relying on the local slam. But if I set it to some non zero positive integer(say 100). What does it mean? Will it try to do some loop closure within the only submap present? For me it deteriorates the result and the result looks better with this param set to 0. Can some one please explain why is it so? 

Besides this I have normally seen in most of the demo files that, the above two parameters are normally set to be equal, is it something which is generally expected?

**Comment by ojura** [comment]
Loop closures are not the only thing affecting the optimization problem. In this case you certainly don’t have any. You also have IMU and odometry data, along with local slam poses, which are inserted as „intra“ constraints.

Having a single submap is weird, though. You can also set the constraint builder sampling ratio to zero to disable generating loop closures, while still having regularly sized submaps.

**Comment by ojura** [comment]
Check out the following lines:
https://github.com/googlecartographer/cartographer/blob/b841ebf170ad4e8c5d8dc731bd28c2fece1ad005/configuration_files/pose_graph.lua#L66-L71

**Comment by SubMishMar** [comment]
Thanks @ojura for your prompt answer! But for me, using no submaps and turning off global optimization gives better results. Is there any guide on tuning the parameters mentioned in : 
https://github.com/googlecartographer/cartographer/blob/b841ebf170ad4e8c5d8dc731bd28c2fece1ad005/configuration_files/pose_graph.lua#L66-L71

My range scan has a very low FOV (60 degree) and I use just wheel odometry at the moment, do you have any tuning guide for such a scenario?

**Comment by SubMishMar** [comment]
And I took your suggestion of setting `POSE_GRAPH.constraint_builder.min_score = 0.0`
And 
```
POSE_GRAPH.optimize_every_n_nodes = 100
TRAJECTORY_BUILDER_2D.submaps.num_range_data = 100
```
And I see some sort of global optimization taking place which screws the map with time.

**Comment by ojura** [comment]
From my experience with a Pioneer P3-DX without an IMU, using odometry in the pose graph sucks. Set `odometry_*_weight` to zero.

> But for me, using no submaps and turning off global optimization gives better results.

Yeah, but using a single submap still makes little sense. Trajectory optimization should be a no-op if you have many submaps and no loop closures. Try setting the odometry weights in pose graph to zero.

**Comment by SubMishMar** [comment]
Makes sense. Let me try with these suggestions.

**Comment by SubMishMar** [comment]
For the record, I am using the real time correlative scan matcher also because it gave me superior results. And I dont trust my prior the the local SLAM scan matcher so I set 
```
TRAJECTORY_BUILDER_2D.ceres_scan_matcher.translation_weight = 5
TRAJECTORY_BUILDER_2D.ceres_scan_matcher.rotation_weight = 0.1
```
Isn't it same as giving low preference to Odometry?

**Comment by ojura** [comment]
Yes, but that's local SLAM. The weights I was talking about are the weights for odometry in the pose graph. Cartographer uses odometry/imu data twice: first during local SLAM, in the _pose extrapolator_ which outputs a prior for scan matching. The second use is in global SLAM, when optimizing the pose graph.

**Comment by SubMishMar** [comment]
I have some follow up questions.

First, the pose extrapolator: does it contain the odometry pose or the cartographer optimized pose? Or till time t-1 it has the optimized pose and at time t(at which the odometry comes in) it has the odometry pose?  

Second, I thought that the global slam does not use any odometry result and just uses the local slam optimized scan position, the associated scans and the submap position. Why does the global slam use odometry?

**Comment by ojura** [comment]
Pose extrapolator is simply [filled up](https://github.com/googlecartographer/cartographer/blob/3f3428e8d437f5d8172238dddec1878efe82f671/cartographer/mapping/internal/2d/local_trajectory_builder_2d.cc#L315) with IMU/odometry measurements. During scan matching, it [provides a prior pose](https://github.com/googlecartographer/cartographer/blob/3f3428e8d437f5d8172238dddec1878efe82f671/cartographer/mapping/internal/2d/local_trajectory_builder_2d.cc#L224).

For your second question, here's the PR which introduced that, maybe you'll understand their motivation: https://github.com/googlecartographer/cartographer/pull/456. I remember that one well because I had to patch it out, since it yielded worse results for me.

**Comment by SubMishMar** [comment]
@ojura also I think the local slam pose estimate is also pushed into the extrapolator, https://github.com/googlecartographer/cartographer/blob/3f3428e8d437f5d8172238dddec1878efe82f671/cartographer/mapping/internal/2d/local_trajectory_builder_2d.cc#L244

Thanks for referencing me to the second link, I will take a look.

**Comment by SubMishMar** [comment]
@ojura If we just consider Local SLAM, Wouldn't the following block diagram broadly summarize the logical flow of the process. Submap is named as Map here.
![capture](https://user-images.githubusercontent.com/28704031/43680344-5cc64988-97ed-11e8-86d7-2746c3908f54.PNG)

**Comment by ojura** [comment]
Yes, that's it. The terminology for the scan matched pose would be a "local pose" (we call optimized poses those which have been optimized by global SLAM). The map updater is a "range data inserter".

Also, each scan is inserted into two most recent submaps (except those at the beginning). Scan matching is performed against the second last submap (the more complete one). 

There's a similar diagram here: https://google-cartographer.readthedocs.io/en/latest/

**Comment by SubMishMar** [comment]
Okay that's cool! 
Although I understand why the scan matching is done against the second last submap, I don't understand why the range scan is also inserted to the second last submap? Shouldn't it be only inserted into the last submap?

**Comment by ojura** [comment]
Inserting the scan is the same as updating the submap, not sure what you mean by „updating at the end of the local SLAM process“.

Inserting the scan to two submaps ensures there‘s a nice overlap between them. If the submap size is 100 scans, it will look something like this:

Scan no. | Event
0  Submap 0 started
50 Submap 1 started
100 Submap 0 finished, submap 2 started
150 Submap 1 finished, submap 3 started
Etc.

So each submap shares 50% of its scans with the previous submap and the other 50% with the next submap. When global SLAM closes loops, the submaps are repositioned and reoriented, and I think having them overlap with each other yields less artifacts at submap borders, when you display the complete map made by superimposing all submaps. Perhaps there‘s another reason, one of the maintainers might know more.

**Comment by SubMishMar** [comment]
Thank you! This answers a lot of questions. I do understand that  inserting a scan is same as updating a submap. But I didn't know about the overlap thing. Thanks.
