### ISSUE TITLE
Is there pose topic published already in 2D pure-localization mode,or I need to calculate it by my own?

### ISSUE THREAD

**Issue by ZhouYixuanRobtic** [googlecartographer/cartographer_ros#976]
Hi,I'm working with cartographer 2D pure localization mode and it works well.Thanks for developers' excellent work. 
In localization mode, I wanna get the robot pose which is not published (May published,but I didn't see it in `rostopic list`). **I am wondering if there's pose topic publihsed already,or I need to calculate it by my own?**
I notice that in the tf topic,the cartographer published the tf between map and odom also odom and base-link. Should I use these two tf to calculate the robot pose?

**Comment by cschuet** [comment]
We publish the pose of the robot as a TF transform. The frame_ids depend on your configuration, but usually base_link (this is your robot) to map (this is origin of the map you are localizing against).

**Comment by ZhouYixuanRobtic** [comment]
Thanks for your help. My query is well answered. Thanks again for your kindly help. Now I'll close this issue.
