### ISSUE TITLE
how can I install imu into cartographer? 

### ISSUE THREAD

**Issue by forlinchow** [googlecartographer/cartographer_ros#985]
I'm using rplidar to do 2d SLAM, and I change to tracking_frame to match the laser data.

now I buy a new 9dof imu and hope the imu data can help it correct the map.( because sometime we can't keep it perfectly horizontal.

**Comment by forlinchow** [comment]
and I already setup the imu.  

I can see the imu data and the /imu topic in rostopic

**Comment by kdaun** [comment]
What is your question?
What do you need help with?

If you want to use the IMU messages in Cartographer you need to:

1. Remap your imu message topic to `imu`
2. Enable using IMU in your Cartographer configurations file
3. Add the IMU link to your URDF

Check the [documentation](https://google-cartographer-ros.readthedocs.io/en/latest/ros_api.html) for more information and see the [backpack2d launch and configuration files](https://github.com/googlecartographer/cartographer_ros/tree/master/cartographer_ros) as an example for 2D SLAM with IMU.

**Comment by forlinchow** [comment]
Does it need to initialize?






------------------ 原始邮件 ------------------
发件人: "Kevin Daun"<notifications@github.com>;
发送时间: 2018年8月21日(星期二) 下午4:11
收件人: "googlecartographer/cartographer_ros"<cartographer_ros@noreply.github.com>;
抄送: "."<544219700@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [googlecartographer/cartographer_ros] how can I install imu intocartographer?  (#985)




What is your question?
 What do you need help with?
 
If you want to use the IMU messages in Cartographer you need to:
  
Remap your imu message topic to imu
 
Enable using IMU in your Cartographer configurations file
 
Add the IMU link to your URDF
  
Check the documentation for more information and see the backpack2d launch and configuration files as an example for 2D SLAM with IMU.

**Comment by kdaun** [comment]
Cartographer supports calibrating the orientation of the IMU, however the general transform between LiDAR and IMU has to be provided by in the URDF. 
An example is given in setup for [backpack_2d](https://github.com/googlecartographer/cartographer_ros/tree/master/cartographer_ros).
See the [configuration documentation](https://google-cartographer-ros.readthedocs.io/en/latest/configuration.html) for an general overview on setting up your TF/URDF.

**Comment by forlinchow** [comment]
thanku

**Comment by duandongbin000** [comment]
which type of imu is used in cartographer official website bags ？
